### ISSUE TITLE
Mise en place MViewer vierge

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#1]
https://github.com/sigrennesmetropole/mviewer 
Branche RM-master

**Comment by cbriand** [comment]
Le Mviewer vierge correspond à la branche RM-master du projet github Mviewer du SIGRM : https://github.com/sigrennesmetropole/mviewer

**Comment by Gaetanbrl** [comment]
@cbriand  je viens de tester les données de test et je vois que lorsqu'on clique sur un point qui en fait correspond à plusieurs points (tous à la même localisation donc), il n'est pas possible de les consulter avec votre mode d'affichage du template de base (qui est celui modifié par RM je pense).

On ne peut en effet pas aller jusqu'en bas.

![image](https://user-images.githubusercontent.com/16317988/86895699-26e8a700-c105-11ea-9597-128b6e76a98e.png)


En l'état, je me demande s'il n'est pas mieux de passer sur un Mviewer "d'origine" car les personnalisation du coeur du Mviewer Rennes Métropole peuvent générer des effets de bord de ce type alors que l'application n'en a potentiellement pas besoin.

**Comment by pcocheril** [comment]
@Gaetanbrl avant même de discuter de cette opportunité technique, je m'interroge sur l'intérêt de pouvoir consulter la fiche d'info sur chaque point individuel (voir mon autre remarque sur #16 ). Je ne crois pas que cela soit utilisable sous cette forme.

**Comment by Gaetanbrl** [comment]
> je m'interroge sur l'intérêt de pouvoir consulter la fiche d'info
@pcocheril j'ai en effet déjà désactivé l'interrogation de cette couche, je te rejoins sur ce point.

Je remonté ce bug afin que vous en ayez connaissance.
