### ISSUE TITLE
[IHM] Splash screen à développer

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#102]
En tant qu'utilisateur, je souhaite que l'application s'ouvre sur une page qui m'explique le but de la carte et son utilisation

**Comment by cbriand** [comment]
A préciser par le Bureau des Temps et la Com

**Comment by cbriand** [comment]
Réponse de la com/bureau des temps (y compris le texte du bloc "saisissez vos horaires") : 
[TextesCartoParticipative_v2.docx](https://github.com/sigrennesmetropole/cartoHoraires/files/5128942/TextesCartoParticipative_v2.docx)

**Comment by Agath21** [comment]
Ajout du texte explicatif dans la box de contribution 
![image](https://user-images.githubusercontent.com/22764056/91302945-87ac6b80-e7a7-11ea-900e-bd2294d1028e.png)

**Comment by cbriand** [comment]
Je pense que ce texte contient plusieurs propositions sur lesquelles la com n'a pas pu statuer.

Essayons 
"Cette carte repose sur les horaires renseignés par des contributeurs volontaires.
Vous souhaitez vous aussi renseigner vos horaires d'arrivée et de départ du travail ? c'est par ici"

**Comment by Agath21** [comment]
Oui je n'ai pas fais attention. J'effectue la modif

**Comment by Agath21** [comment]
![image](https://user-images.githubusercontent.com/22764056/91303513-6d26c200-e7a8-11ea-8155-8b0425cdae50.png)

**Comment by cbriand** [comment]
Super. Je viens de valider ce texte avec Catherine.

**Comment by Agath21** [comment]
Création du module d'accueil avec un système d'onglets pour naviguer entre les 3 rubriques :
- Accueil
- Comment ça marche ? 
- Données personnelles

![image](https://user-images.githubusercontent.com/22764056/91319518-c3056500-e7bc-11ea-9628-8a2952365b87.png)

**Comment by Agath21** [comment]
![image](https://user-images.githubusercontent.com/22764056/91319655-e7f9d800-e7bc-11ea-937a-6f3a3bc537d1.png)

**Comment by Agath21** [comment]
![image](https://user-images.githubusercontent.com/22764056/91319750-04961000-e7bd-11ea-869a-ccf5e65f0f2e.png)

**Comment by cbriand** [comment]
C'est top! Merci @Agath21

**Comment by Agath21** [comment]
Ajustement des marges pour la version mobile
![image](https://user-images.githubusercontent.com/22764056/91414728-42427980-e84d-11ea-84e6-dd732a91ef4c.png)

**Comment by cbriand** [comment]
OK - validé
