### ISSUE TITLE
Recherche base SIRENE à partir de 3 caractères

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#104]
Actuellement, la recherche entreprise est activée à partir de caractères saisis. De nombreuses entreprises n'ont que 3 lettres dans leur nom (ex : EDF) => Il faut lancer la recherche à partir de 3 caractères saisis

**Comment by Gaetanbrl** [comment]
Paramètre à prévoir dans la config dans ce cas.

**Comment by Gaetanbrl** [comment]
Un paramètre `min` est ajouté dans la config de la recherche d'un établissement.
