### ISSUE TITLE
Recherche base SIRENE - filtre sur établissements actifs

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#105]
Dans les deux barres de recherche établissement (carte + formulaire), ne proposer que les établissements actifs :  attribut "Etat administratif de l'établissement = "Actif"

**Comment by Gaetanbrl** [comment]
Champ ciblé : `etatadministratifetablissement`

**Comment by cbriand** [comment]
En lien avec l'issue #108  : 
 appliquer le filtre directement dans l'appel à l'API  ("&facet=nomunitelegale&refine.etatadministratifetablissement=Actif")
https://data.rennesmetropole.fr/api/records/1.0/search?q=(denominationunitelegale:chevre%20OR%20adresseetablissement:chevre)&dataset=base-sirene-v3-ss&rows=10&facet=nomunitelegale&refine.etatadministratifetablissement=Actif

==> l'API retourne les 10 premiers établissements actifs correspondant à la recherche. Il ne nous est ensuite plus utile de retirer les éléments qui ne nous intéressent pas, et la liste de proposition est plus complète.

Pour des résultats plus complets, je complèterais la recherche avec le critère dénomination usuelle de l'entreprise : 
https://data.rennesmetropole.fr/api/records/1.0/search?q=(denominationunitelegale:chevre%20OR%20adresseetablissement:chevre%20OR%20denominationusuelleetablissement:chevre)&dataset=base-sirene-v3-ss&rows=10&facet=nomunitelegale&refine.etatadministratifetablissement=Actif

**Comment by Gaetanbrl** [comment]
>  appliquer le filtre directement dans l'appel à l'API ("&facet=nomunitelegale&refine.etatadministratifetablissement=Actif")

Ajout d'une configuration `requestParam `dans le fichier config.json pour la configuration de la recherche SIREN tel que : 

```
        "sirenConfig": {
            "filters": ["denominationunitelegale", "adresseetablissement"],
            "operator": "OR",
            "url": "https://data.rennesmetropole.fr/api/records/1.0/search",
            "dataset": "base-sirene-v3-ss",
            "max": 10,
            "min": 2,
            "requestParam": "&facet=nomunitelegale&refine.etatadministratifetablissement=Actif"
        }
```

Cela permettra de rajouter d'autres paramètres de ce type dans l'URL très facilement si vous souhaitez faire d'autres tests ou changer plusieurs fois les paramètres de l'URL.

> Pour des résultats plus complets, je complèterais la recherche avec le critère dénomination usuelle de l'entreprise :

La config te le permet bien de rajouter ce type de filtre sans intervention d'un développeur ou modification du code via l'ajout simple du champ à filtrer dans la liste du paramètre `filters` : 

```
        "sirenConfig": {
            "filters": ["denominationunitelegale", "adresseetablissement", "denominationusuelleetablissement"],
            "operator": "OR",
            ...
        }
```
