### ISSUE TITLE
Position du résultat de la recherche

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#106]
Suite à une recherche d'entreprise ou d'adresse, la carte zoome sur les coordonnées de l'élément sélectionné, mais il n'y a pas de pointeur indiquant la localisation de l'élément sur la carte.

Est-il possible d'ajouter un marqueur de position discret qui ne bloque pas la lisibilité de la carte ?

**Comment by Gaetanbrl** [comment]
> Est-il possible d'ajouter un marqueur de position discret qui ne bloque pas la lisibilité de la carte ?

Oui c'est une évolution possible.

Il faut gérer l'affichage et le fait de masquer le pointeur ou opter pour un pointeur temporaire.

**Comment by Gaetanbrl** [comment]
La punaise sera laissée et ne pourra pas être supprimée.

**Comment by Gaetanbrl** [comment]
Evolution réalisée dans la branche 115.

>La punaise sera laissée et ne pourra pas être supprimée.

j'ai rajouté un comportement (proposition).

Lorsqu'un utilisateur réalise une recherche, le picto à gauche change pour afficher une croix, devient cliquable et permet ainsi de supprimer le résultat sur la carte uniquement.

![image](https://user-images.githubusercontent.com/16317988/91733690-2f5fda00-ebaa-11ea-878b-9988e59f48d5.png)

![image](https://user-images.githubusercontent.com/16317988/91733728-3ab30580-ebaa-11ea-96c5-7719b98bd1e5.png)


Lorsqu'un utilisateur clic sur la croix, le picto est donc supprimé de la carte et le picto initial (la loupe) s'affiche.

![image](https://user-images.githubusercontent.com/16317988/91733747-41da1380-ebaa-11ea-873b-5e0ba7eefd78.png)

**Comment by Gaetanbrl** [comment]
A fermer si validé suite à la PR #120

**Comment by cbriand** [comment]
validé
