### ISSUE TITLE
Recherche base SIRENE - cas sans dénomination légale

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#108]
Gérer les cas où la dénomination légale de l'entreprise n'est pas renseignée selon l'algorithme suivant : 
Si dénomination légale est renseignée alors
    `dénomination `= `dénomination légale`
Sinon si dénomination usuelle est renseignée alors
    `dénomination `= `dénomination usuelle`
Sinon 
    `dénomination `= `Prénom de la personne physique`  + `nom de la personne physique` (ou utiliser l'attribut `l1_adressage_unitelegale`)
Fin Si

**Comment by Gaetanbrl** [comment]
Merci pour cette spécification clairement utile.

**Comment by Gaetanbrl** [comment]
Inspection dans le jeux de données : 

* Dénomination legale => denominationunitelegale 
* Dénomination usuelle => à quoi correspond ce champ ?
* Prénom de la personne physique => prenom1unitelegale ?
* Nom de la personne physique => A quoi correspond ce champ ?
* l1_adressage_unitelegale => OK


Merci pour tes précision @cbriand .

**Comment by Gaetanbrl** [comment]
Voici la liste des champs disponibles : 

"datasetid":"base-sirene-v3-ss",
"recordid":"9e7d20c8a1d7b144ca34a7e99d42b78c3f943c6d",
"fields":{
"geolocetablissement":[
48.105032,
-1.650515
],
"siretsiegeunitelegale":"31312967800014",
"soussectionetablissement":"Commerce de detail alimentaire",
"activiteprincipaleunitelegale":"62.43",
"sexeunitelegale":"Masculin",
"adresseetablissement":"BD VILLEBOIS MAREUIL",
"caractereemployeurunitelegale":"Non",
"classeetablissement":"Commerce de detail des viandes",
"l1_adressage_unitelegale":"Monsieur PATRICK ORANGE",
"prenomusuelunitelegale":"PATRICK",
"prenom1unitelegale":"PATRICK",
"activiteprincipaleetablissement":"62.43",
"datefermetureetablissement":"1985-12-25",
"libellevoieetablissement":"VILLEBOIS MAREUIL",
"populationcommuneetablissement":211373,
"siren":"313129678",
"naturejuridiqueunitelegale":"Entrepreneur individuel",
"nomenclatureactiviteprincipaleunitelegale":"NAP",
"statutdiffusionunitelegale":"O",
"datedebutunitelegale":"1985-12-25",
"nomenclatureactiviteprincipaleetablissement":"NAP",
"filename":"sirene_v3_16",
"divisionunitelegale":"Commerce de detail alimentaire de proximite ou specialise",
"nombreperiodesetablissement":1,
"sectionunitelegale":"Commerce",
"sectionetablissement":"Commerce",
"siret":"31312967800014",
"nicsiegeunitelegale":"00014",
"etatadministratifetablissement":"Fermé",
"etatadministratifunitelegale":"Cessée",
"typevoieetablissement":"Boulevard",
"codearrondissementetablissement":"3",
"departementetablissement":"ILLE-ET-VILAINE",
"nic":"00014",
"coderegionetablissement":"53",
"categoriejuridiqueunitelegale":"1000",
"altitudemoyennecommuneetablissement":41,
"codeepcietablissement":"243500139",
"etablissementsiege":"oui",
"codecommuneetablissement":"35238",
"regionetablissement":"BRETAGNE",
"nombreperiodesunitelegale":1,
"datefermetureunitelegale":"1985-12-25",
"superficiecommuneetablissement":5036,
"caractereemployeuretablissement":"Non",
"soussectionunitelegale":"Commerce de detail alimentaire",
"epcietablissement":"Rennes Métropole",
"libellecommuneetablissement":"RENNES",
"divisionetablissement":"Commerce de detail alimentaire de proximite ou specialise",
"unitepurgeeunitelegale":"true",
"nomunitelegale":"ORANGE",
"statutdiffusionetablissement":"O",
"codepostaletablissement":"35000",
"datedebutetablissement":"1985-12-25",
"classeunitelegale":"Commerce de detail des viandes",
"codedepartementetablissement":"35"

**Comment by cbriand** [comment]
Dénomination legale => denominationunitelegale
Dénomination usuelle => denominationusuelleetablissement
Prénom de la personne physique => prenom1unitelegale
Nom de la personne physique => nomunitelegale
1ere ligne d'adressage = l1_adressage_unitelegale (la 1ere ligne d'adressage peut remplacer le couple prénom/nom, mais je ne suis pas sûr que ce soit le plus pratique car ça ajoute un titre Monsieur ou Madame qui peut prendre de la place)

**Comment by Gaetanbrl** [comment]
> pas sûr que ce soit le plus pratique car ça ajoute un titre Monsieur ou Madame qui peut prendre de la place

On va éviter de l'utiliser je pense alors.

merci.

**Comment by Gaetanbrl** [comment]
Par contre pourquoi je ne retrouve pas le champ `denominationusuelleetablissement ` dans mon exemple ? C'est un mauvais résultat sans ce champs que j'ai posté en exemple ?

**Comment by Gaetanbrl** [comment]
J'ai bien intégré le champs mais s'il n'existe pas (lui ou un autre) ce sera transparent.

https://github.com/sigrennesmetropole/cartoHoraires/blob/9f18847177dfba8e8f141009fb7506666b045c92/addons/cartohoraires/js/main.js#L395-L400

**Comment by cbriand** [comment]
C'est parce que l'API ne retourne les attributs que s'ils sont valorisés.

Cas de test : 
N° SIRET = 80308849100011 ==> dénomination légale = 'LES P'TITS KIDS'
N° SIRET = 80239974100015 ==> dénomination légale nulle, dénomination usuelle = 'HM PLOMBERIE CHAUFFAGE'
N° SIRET = 38534316500010 ==> dénomination légale nulle, dénomination usuelle nulle, prénom et nom légaux = 'CHRISTOPHE LUCAS'

**Comment by Gaetanbrl** [comment]
J'ai vu que le champ était bien présent sur certains résultats en effet. Merci.

**Comment by cbriand** [comment]
Je ne comprends pas bien pourquoi, mais cette recherche a un comportement particulier.

**Problème 1 - liste de choix qui ne propose pas tout**
Exemple : si je saisis "Plaisir", j'obtiens 5 résultats, mais si je précise ma recherche "Plaisir d'off", j'ai un seul résultat "PLAISIR D'OFFRIR" qui n'était pas dans la première liste de 5 résultats.
 ==> pourquoi Plaisir d'offrir n'est pas proposé dans la première liste ?

**Problème 2 - sélection inefficace**
J'ai remarqué que parfois, le clic sur une proposition de la liste de recherche n'avait aucun impact (la liste se ferme, mais l'item sélectionné ne s'inscrit pas dans le champ de recherche et la carte ne zoome pas sur la localisation de l'item)
Exemple : dans la liste "Plaisir", la première proposition"MARKET PLAISIR" à Nouvoitou ne fonctionne pas

**Comment by Gaetanbrl** [comment]
> Problème 1 - liste de choix qui ne propose pas tout

Etrange... je ne reproduis pas.

* Saisir "plaisir"
J'ai bien "plaisir d'offrir" etc...

![image](https://user-images.githubusercontent.com/16317988/91448891-c0694500-e87a-11ea-8a58-790f1358ac31.png)

* Saisir "Plaisir d'off"

J'ai bien le même et d'autres.

![image](https://user-images.githubusercontent.com/16317988/91449035-e8f13f00-e87a-11ea-9c09-f26ab7b24cde.png)

**Comment by Gaetanbrl** [comment]
> Problème 2 - sélection inefficace

il semblerait que j'ai une erreur avec ton exemple.

**Comment by Gaetanbrl** [comment]
Le HTML pour ce résultat ne semble pas déclencher correctement la méthode cartohororaires.select()

`<a href="#" onclick='cartohoraires.select("-1.547251,48.041728","MARKET PLAISIR, 21 PL DE L'EGLISE, NOUVOITOU")'>MARKET PLAISIR, 21 PL DE L'EGLISE, NOUVOITOU</a>`

**Comment by Gaetanbrl** [comment]
Je confirme que c'est l'apostrophe qui casse la syntaxe.

![image](https://user-images.githubusercontent.com/16317988/91450244-64072500-e87c-11ea-8793-9a0ae24926f1.png)

**Comment by cbriand** [comment]
Le problème 1 a du se régler avec la correction sur l'appel #105

**Comment by cbriand** [comment]
OK, validé!
