### ISSUE TITLE
[API] - Demande de nouveau mot de passe

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/cartoHoraires#110]
*Lorsque je souhaite utiliser la fonction "code oublié" via l'API avec une adresse qui n'existe pas, la requête me renvoi en premier que le compte n'existe pas: OK
`{success: true, exist: false}
`

*Lorsque je souhaite utiliser la fonction "code oublié" via l'API avec cette même adresse qui n'existe toujours pas car je n'ai pas crée de compte entre temps, la requête me renvoi que le compte existe bien : KO
`{success: true, exist: true}
`

Le compte ne devrait pas exister. La demande d'un mot de passe oublié ne doit pas créer de compte. Autrement, il se peut qu'il y ait des comptes "morts" avec de fausse adresse (erreurs de saisies ou autre).

**Comment by cbriand** [comment]
Il faut appeler la fonction /updateUserPassword sur la fonction code oublié à la place de /createUser qui créée l'utilisateur en base

**Comment by Gaetanbrl** [comment]
Autant pour moi je sais pas ce que j'ai fichu hier après-midi pour me planter de nom.
