### ISSUE TITLE
[Saisie] - Mini map de visualisation des la localisation dans le formulaire

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/cartoHoraires#115]
### En tant qu'utilisateur je souhaite pouvoir localiser le résultat de ma recherche dans le formulaire de saisie.

* La carte est par défaut présente avec un fond de plan classique (osm).
* Par défaut, si l'utilisateur n'a jamais saisie d'information ou si elles ont été supprimées, la carte est vide et n'affiche que le fond de plan.
* Si l'utilisateur cherche une adresse ou un établissement et clique sur un résultat proposé, la carte affiche alors un pointeur sur les coordonnées du lieu sélectionné.
* Si l'utilisateur réalise une nouvelle recherche et sélectionne un nouveau lieu, l'ancien lieu existant doit être supprimé avant d'ajouter ce nouveau lieu sur la carte.

### Évolutions possibles :

* l'utilisateur peut masquer ou afficher la mini map (collapse)
* L'utilisateur souhaite préciser le lieu en déplaçant l'icône ou le pointeur de la carte à l'aide de la souris.
* L'utilisateur peut saisir des coordonnées pour préciser le lieu.

**Comment by Gaetanbrl** [comment]
@cbriand est-il possible de tester la branche feature-115 pour tester cette fonctionnalité ?

Il me restera à peupler les données d'un user vers la carte (getUserInfo).

**Comment by cbriand** [comment]
Le principe de cette carte me convient très bien.
Quelques remarques : 
 - charger la carte sur l'emprise de la métropole par défaut
 - utiliser le fond de plan WMTS "pvci_nb" (plus facile à lire que PVCI simple gris et moins voyant que le PVCI de base)
 - pour un rendu plus homogène, élargir la carte de la taille du composant de recherche (barre + boutons radio) si possible
 - taille en mode mobile à revoir

**Comment by Gaetanbrl** [comment]
> charger la carte sur l'emprise de la métropole par défaut
OK

> pour un rendu plus homogène, élargir la carte de la taille du composant de recherche (barre + boutons radio) si possible

Ce rendu convient ?

![image](https://user-images.githubusercontent.com/16317988/91817715-a7271680-ec35-11ea-8021-7f6df78cbbcd.png)


> pvci_nb

Ok je change.

> taille en mode mobile à revoir

C'était en RAF si le reste est validé.

**Comment by Gaetanbrl** [comment]
En mobile

![image](https://user-images.githubusercontent.com/16317988/91822098-91b2ec00-ec37-11ea-8ede-4c7666ed1bd4.png)

**Comment by Gaetanbrl** [comment]
A fermer si validé suite à la PR #120

**Comment by cbriand** [comment]
à la sélection d'un établissement ou d'une adresse, utiliser le niveau de zoom 17 au lieu de 15. La localisation du point sera plus lisible.

**Comment by Gaetanbrl** [comment]
Modification faite dans 07b2205cb4bb15cf1623aa54acdb17f947258401
