### ISSUE TITLE
clockpicker en position figée sur l'écran

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#125]
Les composants clockpicker ne se déplacent pas en même temps que l'écran. 
Si j'ouvre le clockpicker d'arrivée du lundi, que je descend la page pour voir les autres jours, le composant reste bloqué à sa position initiale sur l'écran

**Comment by Gaetanbrl** [comment]
Idem, je reproduis.

Une règle CSS a dû être ajoutée pour provoquer ce comportement.

**Comment by Gaetanbrl** [comment]
Après inspection je n'observe pas de règle particulière pouvant provoquer ce problème.

**Comment by Gaetanbrl** [comment]
Je propose de fermer le clockpicker au défilement de l'écran (scroll).

**Comment by cbriand** [comment]
validé
