### ISSUE TITLE
Absence ou horaires

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#127]
Lorsque le bouton radio absence d'un jour est coché, rendre les composants de saisie d'horaire et de moyen de transport de ce jour inactifs (et inversement quand le bouton radio est décoché).

Il n'est pas utile de vider les champs d'horaires ou de moyen de transport quand ils sont inactifs.

**Comment by Gaetanbrl** [comment]
Quel est le rendu du statut "inactif" ?

**Comment by cbriand** [comment]
Pas d'action possible sur le composant et le pointeur de souris de type "not-allowed"

**Comment by Gaetanbrl** [comment]
> Pas d'action possible sur le composant et le pointeur de souris de type "not-allowed"

Ok

> Il n'est pas utile de vider les champs d'horaires ou de moyen de transport quand ils sont inactifs.


L'API ne le permet de toute façon pas. Il faut des valeurs pour certains attributs (je n'ai pas la liste). Dans tous les cas j'envoi des informations, même les informations par défaut.

**Comment by Gaetanbrl** [comment]
Fix by b8c8b2c4186c59dccb20d246457e4b41f804fec1

**Comment by Gaetanbrl** [comment]
je pense qu'on peut fermer cette issue

**Comment by cbriand** [comment]
Sur une absence, le bouton "horloge" permet toujours d'ouvrir le clockpicker et de changer l'heure. Il faudrait ne pas pouvoir ouvrir le clockpicker dans ce cas.

**Comment by cbriand** [comment]
OK, validé
