### ISSUE TITLE
slider d'heures - crans de déplacement de 45 minutes ?

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#128]
Je n'arrive pas à placer le curseur du slider d'heures sur 8h15. J'ai l'impression que les crans sont espacés de 45 minutes.

**Comment by Gaetanbrl** [comment]
Je n'ai pas ce soucis avec Chrome ni FF.

**Comment by Gaetanbrl** [comment]
C'est par contre très sensible et demande une grande précision.

**Comment by cbriand** [comment]
Le problème m'a été remonté par les métiers aussi. 
Après une utilisation plus poussée, je remarque que ce problème n'arrive qu'autour des ticks du slider (0h, 4h, 8h, 12h, 16h, 20h, 24h),. A droite et à gauche du tick, on se déplace de 45 min, par contre entre les ticks, on se déplace bien de 15 minutes

**Comment by Gaetanbrl** [comment]
### Analyse 

Le paramètre data_slider_ticks_snap_bounds n'existe pas avec un slider instancié via JS : 

http://seiyria.com/bootstrap-slider/

**Exemple avec l'init dans le html directement :**

```
<input id="ex14" type="text" data-slider-ticks="[0, 100, 200, 300, 400]" data-slider-ticks-snap-bounds="30" data-slider-ticks-labels='["$0", "$100", "$200", "$300", "$400"]' data-slider-ticks-positions="[0, 30, 70, 90, 100]" />
```

**Exemple en JS :** 

```
$("#ex14").slider({
    ticks: [0, 100, 200, 300, 400],
    ticks_positions: [0, 30, 70, 90, 100],
    ticks_labels: ['$0', '$100', '$200', '$300', '$400'],
    ticks_snap_bounds: 30
});
```


### Correctif : 

* Utilisé le bon nom de paramètre
* Utiliser la valeur la plus courte positive pour ce paramètre

```
ticks: [240, 480, 720, 960, 1200],
ticks_labels: ['4h', '8h', '12h', '16h', '20h'],
ticks_snap_bounds: '1'
```

**Comment by Gaetanbrl** [comment]
On peut maintenant sélectionner des valeurs autour du point de repère (ex: 12h15) par clic.

**Comment by cbriand** [comment]
validé
