### ISSUE TITLE
Update Infos utilisateur - cas des absences

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#129]
Quand une absence est déclarée sur un jour (bouton radio coché), l'app doit transmettre un seul horaire pour ce jour avec les caractéristiques suivantes : 
- attribut horaire non envoyé
- attribut moytranspid non envoyé
- attribut mouvement non envoyé
- attribut absence = true

**Comment by Gaetanbrl** [comment]
Est-ce compatible avec l'API ?

Des tests d'appels sur les semaines passés revenaient en erreur avec certaines valeurs manquantes.

**Comment by cbriand** [comment]
Normalement oui. Ces champs ne sont pas obligatoire en base et je ne vois rien dans le code de l'API qui pourrait bloquer

**Comment by Gaetanbrl** [comment]
Ok super !

**Comment by Gaetanbrl** [comment]
Lors de la demande de récupération des informations après l'envoi d'informations avec une absence donc sans horaire, moytranspidn mouvement , le front appel la requête getUserInfos 1x mais réceptionne 2 réponses :

* La première est OK avec les informations
* La secondes est KO et fourni une erreur de ce type : 

`TypeError: Cannot read property 'libelle' of undefined`


Je suppose que cela provient de l'API ?

**Comment by Gaetanbrl** [comment]
> Je suppose que cela provient de l'API ?

Je me répond ==> Retour réalisé par Promise code front et non l'API

**Comment by Gaetanbrl** [comment]
Je pense qu'on peut fermer ce ticket.

**Comment by Gaetanbrl** [comment]
Patch Fix dans 87ec43dfa4220e7f5c625739665acab09c77013b

**Comment by cbriand** [comment]
validé
