### ISSUE TITLE
Maquette carte et fonctionnalités 

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#13]
**Description** : Afficher les données sur une carte géographique
**User Voice** : En tant qu'utilisateur, je souhaite visualiser les données sur une carte intuitive, simple et fonctionnelle
**Tests de conformité** : 
 1- Vérifier que la carte dispose des fonctionnalités basiques (déplacement, zoom, dézoom)
 2- Vérifier que la carte dispose d'un composant de recherche de zone/commune pour zoom automatique
 3- Vérifier que la carte dispose d'un composant de changement de jour
 4- Vérifier que la carte dispose d'un composant de changement d'heure
 5- Vérifier que la carte dispose d'un bandeau sur lequel on retrouve un histogramme, le nombre d'utilisateurs ayant saisi des horaires, des statistiques par mode de transport, des statistiques d'absence
 6- Vérifier que la carte affiche les données en mode cluster

**Comment by cbriand** [comment]
composants (slider de temps)
+ visu filtrées par mode de transport
+ recherche et zoom sur une zone
+ bandeau dataviz/stats

**Comment by Agath21** [comment]
Fait ce jour : 

- Maquette de l'interface et des fonctionnalités Dekstop + cas d'utilisation
![image](https://user-images.githubusercontent.com/22764056/86126583-d955b400-bade-11ea-881b-8a24142fa6b4.png)

**Comment by Agath21** [comment]
Fait ce jour

- Maquette de l'interface et des fonctionnalités Mobile
![image](https://user-images.githubusercontent.com/22764056/86126695-0dc97000-badf-11ea-8531-acc5d4f81a5e.png)
![image](https://user-images.githubusercontent.com/22764056/86126770-289be480-badf-11ea-8a67-5df5a2f8aac1.png)

**Comment by Agath21** [comment]
Point avec Gaëtan, en vue de l'échange avec le bureau des temps (02/07) :
**# Trouver un nom d'application**

**# Quelle représentation de l'histogramme  ?** :
- Pouvoir décider, pour une heure précise, de la meilleure journée ?
==> Vu hebdomadaire.
- Pouvoir décider, pour une journée précise, des meilleurs horaires ?
==> Vu quotidienne

# Quelle représentation des chiffres clés ? Signification (absent, présent ...) 

**# Titre des rubriques** = Guider les utilisateurs 
- 1. Rechercher mon lieu de travail
- 2. Filtrer temporel

**Comment by Agath21** [comment]
Lien vers les documents envoyés : https://we.tl/t-f3xJUeEHpK

**Comment by Agath21** [comment]
Modification de la maquette Dekstop suite aux échanges avec le Bureau des temps 
![image](https://user-images.githubusercontent.com/22764056/87066757-600f3d00-c213-11ea-92e9-1e294a39e7d3.png)

**Comment by Agath21** [comment]
Modification de la maquette Mobile suite aux échanges avec le Bureau des temps 
![image](https://user-images.githubusercontent.com/22764056/87067058-d6ac3a80-c213-11ea-801a-d1d596181d86.png)
