### ISSUE TITLE
Mode mobile - affichage du menu 

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#130]
En mode mobile, afficher systématiquement le menu
 - Légende (ouvre la légende)
 - Affiner ma recherche (ouvre le bandeau d'info)
 - Je contribue (ouvre le formulaire)
 - Icône maison (ouvre la fenêtre à propos)

**Comment by cbriand** [comment]
- Légende : OK
- Affiner ma recherche : trop long, à remplacer par "Affiner"
- Je contribue : la fenêtre ne s'ouvre pas
- Icône maison impossible à utiliser : remplacer par "Accueil"

**Comment by Gaetanbrl** [comment]
A fixer ==> Ouverture de la modal au click sur "Contribuer"

**Comment by cbriand** [comment]
Après fermeture de la modale "Contribuer", il n'est plus possible de l'ouvrir depuis le menu.

**Comment by Gaetanbrl** [comment]
> Après fermeture de la modale "Contribuer", il n'est plus possible de l'ouvrir depuis le menu.

Le fix de la #142 devrait résoudre ce problème.

**Comment by cbriand** [comment]
OK, il reste l'ano #148 à traiter plus spécifiquement sur l'entrée "Contribuer" du menu
