### ISSUE TITLE
Pas de mise-à-jour de la carte après saisie de données

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#133]
La carte devrait se mettre à jour après avoir enregistré de nouvelles données ou supprimé un compte via le formulaire.

**Comment by Gaetanbrl** [comment]
J'ai besoin de plus de détail sur les issues.

Peux-tu préciser si on parle de la carte en général ou également les infos ?

**Comment by cbriand** [comment]
Les deux encarts carte + infos devraient intégrer les nouvelles données

**Comment by Gaetanbrl** [comment]
> Les deux encarts carte + infos devraient intégrer les nouvelles données

Les données initiales devront être mises à jour à chaque envoi de données (nouvel appel geoserver).

**Comment by Gaetanbrl** [comment]
Fix dans 87ec43dfa4220e7f5c625739665acab09c77013b

**Comment by cbriand** [comment]
Validé à l'enregistrement des données.
Il faut aussi aussi recharger les données après une suppression de compte (et afficher la carte sur l'emprise optimale calculée sur les données si ce n'est pas compliqué. Si c'est trop complexe ou trop coûteux, on ne recalcule pas l'emprise, mais on recharge les données)

**Comment by Gaetanbrl** [comment]
> Il faut aussi aussi recharger les données après une suppression de compte

Bien vu ! Je modifie cela.

**Comment by Gaetanbrl** [comment]
Update de la layer intégré.

Pour l'update de la layer et de l'extent à la déconnexion (logout), il faudra tester sur la branche feature-130

**Note :** 

La suppression et la déconnexion appel la méthode logout.
C'est à l'appel du logout qu'on réalise le `zoomToExtent `(`utils/formactions.js`) et l'`updateLayer` (méthode du customLayer "etablissement" dans le fichier `customlayers/etablissement.js`).

**Comment by cbriand** [comment]
OK, la carte principale se met bien à jour après suppression ou mise-à-jour des données.
La déconnexion automatique est à suivre dans #135
