### ISSUE TITLE
Données différentes entre carte et chart

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#134]
Les données présentées sur la carte principales ne sont pas les mêmes que celles de l'histogramme. 
C'est visible sur la branche issue-132 qui indique le nombre de features du cluster.
Nous devrions retrouver les mêmes nombres entre la carte et l'histogramme.

![image](https://user-images.githubusercontent.com/38095778/92463697-6fd3df00-f1cc-11ea-94ac-c390f91258fb.png)

**Comment by cbriand** [comment]
Après recherche en base, sur cet exemple, le bon nombre est celui de l'histogramme : 80

```
SELECT h.*
	FROM horaires_flux.horaire h,
		(SELECT ST_buffer(shape,10,'quad_segs=8')::geometry as geom from horaires_flux.horaire where id=16974) buff
	where ST_intersects(h.shape, buff.geom)
	AND jour=1
	and caduc=false
	and horaire between '08:00:00' AND '08:14:59'
	ORDER BY horaire;
```

**Comment by Gaetanbrl** [comment]
J'allais écrire la même chose avec l'explicatif.

* La carte affiche les données selon l'horaire sélectionnée du slider ==> 08:00 précisément selon ton filtrage
Donc dans l'algo actuelle, seules les données qui ont précisément cet horaire seront affichés sur la carte.

* Le graphique regroupe les données à 15 min près donc il va contenir les données >= 08:00 et < 08:15.

On va donc avoir une différence.


**Exemple :** 

![image](https://user-images.githubusercontent.com/16317988/92466718-d4913880-f1d0-11ea-8672-5068b87596ac.png)



- Voici les horaires du cluster : 13 entités à 08:00

["08:00", "08:00", "08:00", "08:00", "08:00", "08:00", "08:00", "08:00", "08:00", "08:00", "08:00", "08:00", "08:00"]


- Voici les horaires regroupés à 15 min dans le graphique : 17 entités >=08:00 et <08:15

["08:00", "08:00", "08:00", "08:00", "08:00", "08:00", "08:00", "08:00", "08:00", "08:00", "08:00", "08:00", "08:00", "08:05", "08:05", "08:10", "08:10"]

**Comment by cbriand** [comment]
Le problème vient du fait que les données ne sont pas regroupées par tranches de 15 minutes pour la carte principale. Les 54 enregistrements correspondent aux données de 08h00 du lundi uniquement, alors qu'on devrait retrouver toutes les données jusqu'à 08h14min59s

**Comment by cbriand** [comment]
Notre analyse s'est croisée et on arrive à la même explication. 
Il faut que la carte présente les données regroupées par tranche, au même titre que l'histogramme.

**Comment by Gaetanbrl** [comment]
Très bien, je vais faire ça. Le besoin n'avait pas été formalisé dans ce sens pour les données sur la carte, uniquement pour l'affichage des pas de temps dans le slider et pour le graph.

Je créé une branche.

**Comment by Gaetanbrl** [comment]
> Je créé une branche.

Non en fait je repars de ta branche 134 vu que ca concerne le cluster on reste dans la même thématique.

**Comment by Gaetanbrl** [comment]
Réalisé dans 14eff1a96c07409c56945713a67321f0f1e43db7

**Comment by cbriand** [comment]
validé
