### ISSUE TITLE
Formulaire : champs d'heure qui ne devraient pas pouvoir être vidés

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#136]
Actuellement, les champs d'heure peuvent être vidés sans bloquer l'enregistrement des données. 
Deux solutions possibles : 
Solution 1 : ajouter un contrôle de validité sur ces champs, empêcher la sauvegarde s'ils sont vides, et informer l'utilisateur
Solution 2 : à l'usage, si les champs heures sont vidés, renseigner automatiquement leur valeur par défaut (08h pour une arrivée, 18h pour un départ).

=> déployer la solution la moins couteuse

**Comment by Gaetanbrl** [comment]
J'ai une préférence pour la Solution 1.

**Comment by Gaetanbrl** [comment]
> J'ai une préférence pour la Solution 1.

Si non absent *

**Comment by cbriand** [comment]
OK pour la solution 1 (si non absent)

**Comment by cbriand** [comment]
validé
