### ISSUE TITLE
mode mobile - Boutons formulaire de saisie

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#137]
En mode mobile, le bouton permettant de remonter l'écran chevauche les boutons en bas du formulaire 
![image](https://user-images.githubusercontent.com/38095778/92884608-499f8080-f412-11ea-809f-2d0969c48616.png)

Il serait préférable d'agrandir le panneau pour que les boutons "Réinitialiser" et "Valider" puissent se retrouver au dessus de la flèche.
Je pense que ce serait plus élégant de centrer horizontalement les deux boutons "Réinitialiser" et "Valider" en bas du panneau (en mode mobile uniquement)

**Comment by Gaetanbrl** [comment]
Bonne issue ! J'avais observé ce comportement et testé un correctif, je ne sais plus si c'est sur une branche en cours... Je regarderai.

**Comment by Gaetanbrl** [comment]
> Je pense que ce serait plus élégant de centrer horizontalement les deux boutons "Réinitialiser" et "Valider" 

Ok pour le centrage. Je vais regarder.

**Comment by Gaetanbrl** [comment]
Comportement après modification : 

![image](https://user-images.githubusercontent.com/16317988/92948867-5fd12f00-f45a-11ea-888a-67495b635665.png)

Testable sur  branche `issue-137` : @cbriand cet affichage convient ?

**Comment by cbriand** [comment]
je ne vois pas la branche issue-137, mais cet affichage me convient

**Comment by Gaetanbrl** [comment]
C'est sur develop autant pour moi.

**Comment by cbriand** [comment]
validé
