### ISSUE TITLE
Messages d'alerte

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/cartoHoraires#139]
Les messages d'alertes doivent permettre d'informer :

* L'utilisateur sous forme de message simple (erreur, succès des requêtes)
* L'utilisateur sous forme de popup en cas de demande de saisie (ex : mot de passe pour confirmation)
* Une log explicite dans la console en cas d'échec d'une requête

Ces messages peuvent être une ligne de texte dans l'IHM (comme actuellement pour préciser qu'un mail vient d'être envoyé) ou bien dans une petite fenêtre type Bootstrap alert.

**Comment by cbriand** [comment]
Liste des messages d'alerte : 
- [ ] Suppression des horaires
- [ ] Tentative de connexion avec de mauvaises données de connexion
- [ ] Demande de mot de passe avec de mauvaises données de connexion
- [ ] Demande de mot de passe avec de bonnes données de connexion
- [ ] Enregistrement des données horaires
- [x ] 1ère connexion

**Comment by Gaetanbrl** [comment]
Petite question, on ferme toute l'interface et on réalise un logout à l'enregistrement des données horaire. 

A quel endroit afficher le message "Enregistrement des données horaires" ?

**Comment by Gaetanbrl** [comment]
> A quel endroit afficher le message "Enregistrement des données horaires" ?

Je propose d'utiliser l'alert native Mviewer 


![image](https://user-images.githubusercontent.com/16317988/94281219-a6d91d00-ff4e-11ea-9c85-9c9b7c256372.png)

**Comment by cbriand** [comment]
Oui, l'alerte native me parait bien si on peut modifier le message en "Informations sauvegardées et utilisateur déconnecté !"

**Comment by Gaetanbrl** [comment]
> si on peut modifier le message en "Informations sauvegardées et utilisateur déconnecté !"

je viens de faire la modification, vous pourrez facilement adapter les messages

**Comment by Gaetanbrl** [comment]
Le système de gestion des messages est localisé ici : 

https://github.com/sigrennesmetropole/cartoHoraires/blob/7b012278f1fa114d63df4f371f0d4581690f3639/addons/cartohoraires/js/utils/messages.js#L19-L20

Vous pourrez donc custom tous les messages. Ces messages ton interprétés come du HTML afin de pouvoir y ajouter des icônes via font-awesome (par défaut) ou Glyphicon (déjà installée avec bootstrap).

Vous pouvez jouer sur la couleur, le text et le temps afin de choisir

**Comment by Gaetanbrl** [comment]
https://github.com/sigrennesmetropole/cartoHoraires/blob/7b012278f1fa114d63df4f371f0d4581690f3639/addons/cartohoraires/js/utils/messages.js#L48

Le code ci-dessus permet de voir les modifications possibles sur un message dans le code: 
* Couleur
* Action à la disparition du message (ex: cacher une modal)
* Le message à afficher (HTML)
* Le temps avant disparition du message (et non son conteneur)

**Comment by cbriand** [comment]
OK, validé avec quelques modifications des libellés dans le fichier cartoHoraires/addons/cartohoraires/js/utils/messages.js
