### ISSUE TITLE
Maquette formulaire de saisie

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#14]
**Description** : Mettre à disposition un formulaire de saisie des données horaires
**User Voice** : En tant qu'utilisateur, je veux pouvoir saisir mes données horaires réguliers sur les jours ouvrés de la semaine
**Tests de conformité** : 
 1- Charger le formulaire vierge
 2- Vérifier qu'il est possible de sélectionner une entreprise depuis la base SIRENE (openData)
 3- Vérifier que sur chaque ligne de jour, il existe des composants de saisie 
       - un horaire d'arrivée
       - le dernier mode de transport utilisée pour l'arrivée
       - un horaire de départ
       - le mode de transport utilisée pour le départ
       - ou déclarer une absence avec la raison
 4- Montrer l’enchaînement de l'activation des composants

**Comment by cbriand** [comment]
Formulaire en modale de la carte

**Comment by Agath21** [comment]
**Version 1**
Maquette de l'interface et des fonctionnalités Dekstop + cas d'utilisation
![image](https://user-images.githubusercontent.com/22764056/87535788-587ae880-c698-11ea-8fe9-e88ed4eebb31.png)

**Comment by Agath21** [comment]
La maquette en version Mobile sera réalisée après correction et validation de la première version lors du point prévu le 17/07

**Comment by Agath21** [comment]
#Version 2
Maquette de l'interface et des fonctionnalités en version mobile 
![image](https://user-images.githubusercontent.com/22764056/89764501-cc23e000-daf4-11ea-8472-d68fba75887b.png)

**Comment by Agath21** [comment]
**Version 3**
Modification de l'interface du formulaire suite au daily du 06/08 : 

- Suppression du titre "Connexion"
- Libellé " Vos horaires ot été copiés jusqu'au vendredi. Vérifiez que les horaires de tous les jours de la semaine sont correctement renseignés."
- En mode connecté, suppression du bouton " Modifier vos horaires" et ajout du bouton "Se déconnecter"
![image](https://user-images.githubusercontent.com/22764056/89766221-1f4b6200-daf8-11ea-8d5b-7b40811e1cdf.png)

**Comment by Agath21** [comment]
**Gestion de la connexion / mode dekstop**
Par défaut, l'utilisateur arrive sur l'interface 1 lui proposant de se connecter. Lorsque celui-ci est connecté, le formulaire de connexion est remplacé par un panel (2) lui indiquant qu'il est identifié sous XXX@xxx.com et lui permettant de supprimer ses horaires et de se déconnecter. 
![image](https://user-images.githubusercontent.com/22764056/89766816-0becc680-daf9-11ea-8ed2-6bd880aba012.png)

**Comment by Agath21** [comment]
**Gestion de la connexion / mode mobile**
![image](https://user-images.githubusercontent.com/22764056/89767002-5cfcba80-daf9-11ea-8f2c-28cb3d36a766.png)

**Comment by Gaetanbrl** [comment]
@Agath21 @cbriand les maquettes sont validées je crois ? 
==> issue à fermer ?
