### ISSUE TITLE
Mauvaises valeurs par défaut après suppression de compte

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#140]
Après avoir supprimé un compte, le formulaire de saisie présente de mauvaises valeurs par défaut (8h en heure de départ, absence = faux sur samedi, dimanche)

**Comment by Gaetanbrl** [comment]
A modifier : 

https://github.com/sigrennesmetropole/cartoHoraires/blob/5c44a33df6eb0a305799c2ebdecd9aa24f85773d/addons/cartohoraires/js/utils/formActions.js#L17-L18

**Comment by Gaetanbrl** [comment]
A valider une fois dispo sur PF de test.

**Comment by cbriand** [comment]
Je me suis mal exprimé. Les valeurs par défaut devraient être :
Heure d'arrivée = 08h00
Heure de départ = 18h00

Actuellement, les deux champs ont la classe "clock" et se voient affectés de la valeur 08h00.

**Comment by Gaetanbrl** [comment]
> Actuellement, les deux champs ont la classe "clock" et se voient affectés de la valeur 08h00.

ok c'est de ma faute, ca me semble assez logique.

**Comment by cbriand** [comment]
ok validé
