### ISSUE TITLE
Problème de chargement de la carte après enregistrement des données

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#141]
La carte principale a du mal à se recharger après l'enregistrement de données horaires : 
- pas de filtre des données
- emprise complète (et pas uniquement sur la zone des horaires précédemment saisis)

![image](https://user-images.githubusercontent.com/38095778/93061369-bebdc080-f673-11ea-88e5-7744cfe1d287.png)

**Comment by Gaetanbrl** [comment]
Problème d'asynchrone à analyser.

**Comment by Gaetanbrl** [comment]
Le style semble ne pas se charger correctement au chargement des données.

Le refresh ne semble pas suffire, il semble que tout le canevas de la carte nécessite d'être recalculé de force via un mouvement type zoom ou recentrage (zoomToExtent).

**Comment by Gaetanbrl** [comment]
> emprise complète (et pas uniquement sur la zone des horaires précédemment saisis)

Je ne comprend pas, actuellement on reclacule la couche (update), on calcule l'étendue et on centre sur l'étendu. Il faut un certain temps entre la fermeture de la modal et le recentrage sur l'emprise.

On constate ensuite les problèmes d'affichage avec le style des cluster sur dimensionnés.

Ce n'est pas ce que tu observes ?

**Comment by cbriand** [comment]
La semaine dernière, tu as soumis la très bonne idée de zoomer sur la zone utile de l'utilisateur après enregistrement de ses données horaires. C'est ce que tu fais à la connexion de l'utilisateur. Il n'est alors pas utile de recalculer l'étendue de la carte principale à la fermeture de la modale.

Pour moi, le calcul de l'étendue de la carte et de son centre ne doit se faire qu'au chargement initial de l'application et pas sur les actions suivantes.

Le problème de style, lui, doit être corrigé.

**Comment by Gaetanbrl** [comment]
Donc si je comprend bien on ne recentre pas sur l'étendue à la deconnexion / suppresion d'un user ?

**Comment by cbriand** [comment]
Non, on peut rester sur la zone qu'il consultait avant de se connecter.

**Comment by Gaetanbrl** [comment]
Très bien, merci pour cette précision.

**Comment by Gaetanbrl** [comment]
@cbriand je viens de pousser un fix pour cette issue. A tester car on a de l'asynchrone (les comportements peuvent changer entre 2 tests dans le pire des cas).

**Comment by cbriand** [comment]
Ca a l'air de fonctionner, mais le rafraîchissement de la carte est long

**Comment by Gaetanbrl** [comment]
c'est normal c'est le temps de la réception de toutes les données (requêtes WFS) et re traitement derrière (filtre attributaire et spatial).

**Comment by Gaetanbrl** [comment]
En contrôlant dans la trame réseau de la console, on peux voire l'écart de temps entre appel - réception de la requête.
