### ISSUE TITLE
Mobile - écran noir après enregistrement des données 

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#142]
Après enregistrement des données, la zone de saisie se ferme, mais le fond grisé ne disparait pas, ni le bouton flèche pour remonter l'écran. Il n'est plus possible de rien faire à partir de là.

Comportement observé sous Chrome et Firefox sous android.

![image](https://user-images.githubusercontent.com/38095778/93064629-09d9d280-f678-11ea-8477-c32eca1a6da8.png)

**Comment by cbriand** [comment]
idem après suppression de compte

**Comment by Gaetanbrl** [comment]
Reproduis avec le mode responsive du navigateur.

**Comment by Gaetanbrl** [comment]
Semble dépendre de la méthode appelée.

**Comment by Gaetanbrl** [comment]
Vu ==> Plusieurs écouteurs au chargement des données (event on postrender sur le customLayer).

Nécessite un seul listener au premier chargement des données.

**Comment by Gaetanbrl** [comment]
A valider une fois dispo sur PF de test.

**Comment by cbriand** [comment]
validé
