### ISSUE TITLE
Formulaire - bouton "Valider" qui reste grisé après geolocalisation

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#143]
Lors du premier enregistrement, le bouton "Valider" est grisé par défaut. 
Il ne se dégrise pas après l'action de géolocalisation même si toutes les données horaires sont correctes.

**Comment by Gaetanbrl** [comment]
Testé sur https://testapp.sig.rennesmetropole.fr/mviewer/?config=apps/cartoHoraires/cartohoraires.xml#

A valider.

**Comment by cbriand** [comment]
validé
