### ISSUE TITLE
Page "Contribuer" s'affiche en mode desktop depuis le menu

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#144]
La page "Je contribue" ouverte depuis le menu mobile (lien "Contribuer") s'ouvre en mode desktop et non mobile.

Après fermeture de cette modale, il n'est plus possible de l'ouvrir depuis le menu.

![image](https://user-images.githubusercontent.com/38095778/93067943-211abf00-f67c-11ea-94bb-bf15d0113c06.png)

**Comment by Gaetanbrl** [comment]
En doublon avec commentaire sur #130 :

>A fixer ==> Ouverture de la modal au click sur "Contribuer"

**Comment by cbriand** [comment]
doublon
