### ISSUE TITLE
Bandeau d'info transparent sur Ipad

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#145]
Sur Ipad (safari ou Chrome), le fond blanc du panneau "Affiner" n'est pas tiré jusqu'en bas du bandeau (même problème que nous avions sur la vue mobile en début de projet. Il faut que le fond blanc fasse la même hauteur que le panneau.

**Comment by Gaetanbrl** [comment]
### Analyse :
Problème provenant du premier élément Bootstrap inséré directement après le début du corps de la modal.

Le code qui, je pense est à analyser et modifié est le suivant : 

https://github.com/sigrennesmetropole/cartoHoraires/blob/3a7c7b5a61e2e5403fa434b244dfe7b9554b619d/addons/cartohoraires/templates/cartohoraires.html#L2-L3


La classe "col-sm-12" est donc potentiellement ce qui pose le problème.

### Solution potentielle : 
Supprimer cette classe puisqu'aucune autre div n'est contenue dans le modal-body.
