### ISSUE TITLE
Pop-up de saisie de code pour suppression des données

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#146]
Nous n'avons pas développé de modale pour la pop-up qui s'ouvre à la demande de suppression des horaires pour demander le code de connexion.
Cette modale devrait réutiliser le style de la modale "code oublié ?"

Titre = Suppression des horaires
Message = Veuillez saisir votre code de connexion pour supprimer vos données horaires. Attention, votre compte sera lui-aussi supprimé avec cette action.
Champ de saisie = 
     classe : "fas fa-key"; 
     message grisé : "XXXXX"
Bouton = "Supprimer les horaires"

![image](https://user-images.githubusercontent.com/38095778/93308380-797bc900-f802-11ea-8920-4a4b21d30500.png)

**Comment by Gaetanbrl** [comment]
En effet j'avais prévu de le faire dans une alerte Bootstrap mais mes tests n'étaient pas concluant avec ce type de popup.

C'est une bonne idée de reprendre cette modal pour les différents messages avec saisie. Je vais adapter le code pour la rendre "générale" et peupler son contenu selon le besoin (html dynamique via JQuery).

**Comment by Gaetanbrl** [comment]
lié avec #139

**Comment by Gaetanbrl** [comment]
Les modals sont gérées dans ce fichier : 

https://github.com/sigrennesmetropole/cartoHoraires/blob/7b012278f1fa114d63df4f371f0d4581690f3639/addons/cartohoraires/cartohoraires.html#L45

**Comment by cbriand** [comment]
Dans cette pop-up, le message n'est pas complet : Veuillez saisir votre code de connexion pour supprimer vos données horaires. Attention, votre compte sera lui-aussi supprimé avec cette action.

**Comment by cbriand** [comment]
validé avec modification dans le fichier cartoHoraires/addons/cartohoraires/cartohoraires.html
