### ISSUE TITLE
Accès via Menu Contribuer mode Mobile

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/cartoHoraires#148]
Le formulaire de saisie ne s'affiche pas en mode mobile avec un appareil mobile. Uniquement si on y accède depuis le menu : 

![image](https://user-images.githubusercontent.com/16317988/94403964-84bde580-016e-11eb-831c-6ed57f46a275.png)

**Comment by cbriand** [comment]
validé
