### ISSUE TITLE
Connexion avec login ou mot de passe vide sans message

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#149]
Si on tente de se connecter avec le champ login ou mot de passe vide, aucun message n'indique l'erreur ==> afficher le message wrongLogin quand l'appel loginUser retourne une exception de code -1 (paramètre manquant)

**Comment by Gaetanbrl** [comment]
Une vérification devrait interdire le clic sur le bouton de login si un des deux paramètres est manquant.

**Comment by cbriand** [comment]
validé
