### ISSUE TITLE
Représentation de l'histogramme

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#15]
Histogramme + courbe de tendance ? (non prioritaire)

**Comment by Agath21** [comment]
L'histogramme devra représenter la répartition des arrivées sur une journée sélectionnée comme ci-dessous 
![image](https://user-images.githubusercontent.com/22764056/87066955-aa90b980-c213-11ea-8244-e1d8288621c6.png)

Pas de temp à définir selon la lisibilité > 15mins ou 30 mins

**Comment by Gaetanbrl** [comment]
Contraintes potentielle : 
Il faudra vérifier que ChartJs puisse afficher des histogrammes au 1/4 d'heure.

**Comment by Agath21** [comment]
Comportement :
- Par défaut, Lundi 9:00 / tous mode de transport confondus / emprise de la carte
- Quand modification du filtre temporel / mode de transport / emplacement de la carte ou ZAC, l'histogramme doit s'adapter aux changements des paramètres
![image](https://user-images.githubusercontent.com/22764056/87067719-baf56400-c214-11ea-80d7-929b4b19c309.png)

**Comment by Gaetanbrl** [comment]
@Agath21 @cbriand 

Testé rapidement avec Chart.JS :

![image](https://user-images.githubusercontent.com/16317988/89042544-604cb500-d347-11ea-8ff8-a834ffb1658b.png)

Ls valeurs en abscisse représentent le nombre de quart d'heure de 7h à 20h comme précisé par Catherine. Soit 80 x 15 min.
Ces valeurs seront remplacées par exemple par `07:15` en respectant des pas de 15 min.


Ce test montre que cette représentation permet la visibilité avec des valeurs simples en étiquette d'axe X.

Avec les heures type `07:05` ce sera cependant moins visible.

**Comment by Gaetanbrl** [comment]
Voici la vue mobile : 

![image](https://user-images.githubusercontent.com/16317988/89042949-11534f80-d348-11ea-8e3b-f2ff5aa38bd0.png)

**Comment by cbriand** [comment]
Vu avec Catherine. La représentation actuelle est OK.
Il n'est pas besoin d'afficher les horaires sans valeur.
Les données présentées doivent être regroupées par tranches de 15 minutes (cf. https://github.com/sigrennesmetropole/cartoHoraires/issues/89)

Petit doute quand les données vont se multiplier, l'axe X va s'élargir. Le diagramme sera-t-il toujours lisible ?

**Comment by Gaetanbrl** [comment]
> Petit doute quand les données vont se multiplier, l'axe X va s'élargir. Le diagramme sera-t-il toujours lisible ?

Il faut tester avec un dataset proche de la réalité.
