### ISSUE TITLE
Affichage des données sur la carte (cluster)

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#16]
**Description** : Afficher sur la carte les données sous forme de clusters 
**User Voice** : En tant qu'utilisateur, je veux pouvoir consulter les données horaires sur la carte
**Tests de conformité** : 
 1- Charger la carte
 2- Vérifier que les données s'affichent sous forme de clusters (cercles de tailles variables selon le volumes de saisies correspondantes au point et nombre de saisies concernées affiché au centre du cercle)
 3- Vérifier que seules les données de présence sont prises en compte dans l'affichage (les absences ne sont pas visibles sur la carte)
 4- Zoomer sur la carte
 5- L'affichage devient plus précis sur les points

**Comment by Gaetanbrl** [comment]
- [ ] Géocoder les données tests
- [ ] Créer la couche dans Mviewer (custom)
- [ ] Gérer le style OL de la couche (cluster)
- [ ] Charger la carte
- [ ] Vérifier que les données s'affichent sous forme de clusters (cercles de tailles variables selon le volumes de saisies correspondantes au point et nombre de saisies concernées affiché au centre du cercle)
- [ ] Vérifier que seules les données de présence sont prises en compte dans l'affichage (les absences ne sont pas visibles sur la carte)
- [ ] Zoomer sur la carte
- [ ] L'affichage devient plus précis sur les points

**Comment by Gaetanbrl** [comment]
> L'affichage devient plus précis sur les points

Est-ce qu'il souhaité de ne voir que des points simple ou bien il est nécessaire de laisser une représentation en mode "cercle proportionnel" au zoom proche (à la rue) @cbriand @Agath21 ?

**Comment by Gaetanbrl** [comment]
![image](https://user-images.githubusercontent.com/16317988/86900520-bbee9e80-c10b-11ea-9637-4e29156fdc10.png)

**Comment by pcocheril** [comment]
@Gaetanbrl On risque d'avoir beaucoup de points superposés, pour toutes les réponses d'une même entreprise ou de plusieurs entreprises dans le même bâtiment. Pour moi, il faut que la représentation reste proportionnelle, même en zoom à la rue.

**Comment by Gaetanbrl** [comment]
A l'affichage ce n'est pas très problématique d'avoir plusieurs points puisque nous n'en verront qu'un seul avec la gestion des symbologies OpenLayers.

> Pour moi, il faut que la représentation reste proportionnelle, même en zoom à la rue.

Cette représentation me convient également.

Dans les deux cas, la complexité de réalisation est faible pour passer du mode vue cluster à la vue ponctuelle simple selon l'échelle.

**Comment by Gaetanbrl** [comment]
Je laisse en cluster, on pourra toujours en reparler avec Catherine si besoin.
