### ISSUE TITLE
Filtrage du layer : mode de transport

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#17]
**Description** : Afficher sur la carte les données correspondant aux critères de mode de transport sélectionnés
**User Voice** : En tant qu'utilisateur, je veux pouvoir choisir les données correspondant à un ou plusieurs mode de transport 
**Tests de conformité** : 
 1- Charger la carte
 2- Vérifier qu'il existe un composant de sélection des modes de transport
 3- Vérifier que tous les modes de transport sont sélectionnés par défaut
 4- Décocher un mode de transport
 5- Les données affichées sur la carte et le bandeau correspondent aux modes de transports sélectionnés
 6- décocher tous les modes de transport
 7- Aucune donnée n'est affichée sur la carte. Le bandeau affiche les statistiques d'absence uniquement

**Comment by Gaetanbrl** [comment]
- [ ] Insérer liste (UI)
- [ ] Peupler les valeurs selon les infos contenues dans la couche (comportement temporaire -> Pourra être issue de valeurs fix ou d'une API)
- [ ] Refresh cluster à la sélection dans la liste
- [ ] Refresh infos et graphique
