### ISSUE TITLE
Filtrage du layer : temps/horaires

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#18]
**Description** : Afficher sur la carte les données correspondant aux critères de temps sélectionnés
**User Voice** : En tant qu'utilisateur, je veux pouvoir choisir le jour et l'heure d'affichage des données et consulter les données correspondantes
**Tests de conformité** : 
 1- Charger la carte
 2- Vérifier qu'il existe un composant de sélection de jour et un composant de sélection d'heures
 3- Vérifier que les curseurs des deux composants sont sur les positions par défaut pré-sélectionnées par la configuration de la carte (jour J et heure H)
 4- Déplacer le curseur de jours d'un cran
 5- Les données affichées sur la carte et le bandeau correspondent au jour J+1, à l'heure H
 6- Déplacer le curseur d'heure d'un cran
 7- Les données affichées sur la carte et le bandeau correspondent au jour J+1, à l'heure H+15min

**Comment by Gaetanbrl** [comment]
- [ ] Insérer jours cliquables (UI)
- [ ] Récupérer les jours selon une API ou en dur (actuellement en dur)
- [ ] Refresh cluster à la sélection d'une journée
- [ ] Refresh infos et graphique
