### ISSUE TITLE
Légende ?

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#19]
**Description** : Afficher une légende correspondant aux données de la carte
**User Voice** : En tant qu'utilisateur, je veux disposer d'une légende qui m'informe des données affichées sur la carte
**Tests de conformité** : 
 1- si je clique sur le bouton "légende", alors le panneau se déplie et explique les cluster bleus de données horaires et les emprises oranges de ZAC

**Comment by Gaetanbrl** [comment]
Ajout d'une légende simple à valider.
@Agath21  une autre idée ?

![image](https://user-images.githubusercontent.com/16317988/91204280-21224180-e704-11ea-8f1b-f3961afaa56d.png)

**Comment by cbriand** [comment]
Je parlerais plus de "volume de déplacements" plutôt que nombre de personnes

**Comment by Gaetanbrl** [comment]
**Proposition pendant le daily ** : 
* Nombre d'arrivées / départs
* Rajouter la légende pour les ZAC

**Comment by Agath21** [comment]
Modifications réalisées :
- Création d'une image pour la légende
- "Flux de personnes" remplacé par "Légende"
- Suppression de la croix via le paramètre "permanentlayer"
![image](https://user-images.githubusercontent.com/22764056/91283702-3aba9c00-e78b-11ea-8bfe-67e0f002c7a4.png)

**Comment by Agath21** [comment]
Harmonisation des couleurs des ZAC sur la carte avec l'application // + distinction avec les arrivées : 
- ZAC par défaut en bleu marine
- ZAC sélectionnée en jaune 
![image](https://user-images.githubusercontent.com/22764056/91284290-ff6c9d00-e78b-11ea-9ea0-360288f9f64b.png)

**Comment by Gaetanbrl** [comment]
Permanent layer disponible sur develop.

**Comment by cbriand** [comment]
validé
