### ISSUE TITLE
Dossier app - mviewer / carte initiale

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#2]
cf. dossier apps/cartohoraires du projet https://github.com/sigrennesmetropole/mviewer (branche RM-master)

**Comment by cbriand** [comment]
Zoom initial sur rennes métropole

**Comment by Gaetanbrl** [comment]
Le repository  https://github.com/sigrennesmetropole/cartoHoraires contiendra donc le contenu du repo suivant : 

* https://github.com/sigrennesmetropole/mviewer/blob/RM-master/apps/cartohoraires/

Il faudra intégrer le contenu du repository https://github.com/sigrennesmetropole/cartoHoraires comme un submodule git dans le repo `apps/cartohoraires`.

![image](https://user-images.githubusercontent.com/16317988/86243744-2f8e2a00-bba7-11ea-89ce-dc1793e77459.png)

**Comment by Gaetanbrl** [comment]
Je modifie l'emplacement de cette issue qui n'est pas "Done" mais en "in progress".
Car la structure de l'application cartographique doit être dans le repos https://github.com/sigrennesmetropole/cartoHoraires/ avec ce fonctionnement.

**Comment by Gaetanbrl** [comment]
Les éléments ont été placés dans ce repository : 

https://github.com/sigrennesmetropole/cartoHoraires


@cbriand il vous faudra récupérer cette application dans sigrennesmetropole/mviewer/apps comme un sous-module.

**Comment by Gaetanbrl** [comment]
Je viens de porter le sous module dans sigrennesmetropole/mviewer/apps via ce commit : 
https://github.com/sigrennesmetropole/mviewer/commit/eebfa540d3921e15f054222bfa145e0f14885220
