### ISSUE TITLE
Duplication données du lundi sur les autres jours

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#22]
**Description** : Dupliquer automatiquement les données saisies sur le lundi sur les autres jours de la semaine
**User Voice** : En tant qu'utilisateur, je veux bénéficier d'un système de saisie qui m'évite de saisir des données récurrentes tous les jours de la semaine.
**Tests de conformité** : 
 1- Charger un formulaire de saisie vierge
 2- Vérifier que seul le lundi est saisissable
 3- Saisir l'heure d'arrivée du lundi et passer au composant suivant
 4- Les jours de mardi à vendredi sont éditables et l'heure d'arrivée du lundi est dupliquée sur ces jours
 5- Répéter l'opération sur chaque composant vierge du lundi
 6- La valeur est dupliquée sur chaque jour
 7- Modifier une valeur existante du lundi
 8- la valeur n'est pas dupliquée sur les autres jours
 9- Vider un composant du lundi, sortir puis saisir une nouvelle valeur
 10- la valeur n'est pas dupliquée sur les autres jours
 11- Sur chaque jour, disposer d'un bouton pour vider la ligne
 12 - Utiliser le bouton du lundi
 13 - la ligne du jour se vide sans impacter les autres jours
 14 - répéter l'opération sur tous les autres jours
 15 - la ligne du jour se vide sans impacter les autres jours
 16- Lorsque tout le formulaire est vide, seule la ligne du lundi est éditable
 17- Renseigner les valeurs du lundi
 18- Les valeurs sont dupliquées sur les autres jours
 19- Disposer d'un bouton "Réinitialiser"
 20- Cliquer sur le bouton "Réinitialiser"
 21- Le formulaire se vide, seule la ligne du lundi est éditable

**Comment by cbriand** [comment]
+ Horaires
+ Mode de transport
+ Absence

**Comment by cbriand** [comment]
Copie des données du lundi sur les autres jours
Bouton "réinitialiser" pour vider le formulaire
Possibilité de vider la ligne d'un jour
Ne pas dupliquer les données du lundi si autres jours renseignés

**Comment by Gaetanbrl** [comment]
> Copie des données du lundi sur les autres jours

OK

> Bouton "réinitialiser" pour vider le formulaire

Le formulaire n'est jamais "vide" mais contient des valeurs par défaut.

> Possibilité de vider la ligne d'un jour

Une journée n'est jamais "vide" mais contient des valeurs par défaut.

> Ne pas dupliquer les données du lundi si autres jours renseignés

Duplication au choix sans event ou automatisme risqués (risque d'erreurs et de supprimer les autres jours saisis involontairement).

**Comment by Gaetanbrl** [comment]
Bouton ajouté pour remettre par défaut les valeurs du formulaire (même si les données ont étaient récupérées depuis la base) :

fdb3bf3ff6d20f21f51cd86b03a58e58e5bf4554

**Comment by cbriand** [comment]
Retirer le bouton de copie et le texte d'aide des jours samedi et dimanche

**Comment by Gaetanbrl** [comment]
Une personne qui travail du mardi au samedi (commerce, restauration) ne pourront donc jamais dupliquer les horaires ?

**Comment by cbriand** [comment]
Si, puisqu'on conserve le bouton sur le mardi, mercredi, jeudi et vendredi. 
Le cas du samedi sera à saisir manuellement.

**Comment by Gaetanbrl** [comment]
Donc en effet ils ne pourront jamais dupliquer le samedi ou dimanche ni vers les autres jours ni des autres jours vers ces deux jours.

Donc on impose une double saisie forcé pour ce type d'utilisateur. Quelle est la valeur ajouté d'enlever ce bouton pour les samedi et dimanche  ?

**Comment by Gaetanbrl** [comment]
> Retirer le bouton de copie et le texte d'aide des jours samedi et dimanche

Fait dans 4a35c6032bb1f005c4cb17f2f813e18c3e313f1a

**Comment by cbriand** [comment]
La valeur ajoutée est de montrer que ces deux jours ont un fonctionnement différent. Au premier regard, l'utilisateur s’aperçoit qu'il manque quelque chose sur ces deux jours et est plus vigilent.

**Comment by Gaetanbrl** [comment]
Je pense qu'on peut fermer cette issue

**Comment by cbriand** [comment]
OK, validé
