### ISSUE TITLE
Recherche et zoom sur élément sélectionné

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#26]
**Description** : Permettre un zoom rapide sur des zones particulières (commune, zone d'activité)
**User Voice** : En tant qu'utilisateur, je veux pouvoir sélectionner une commune ou une zone d'activité et que la carte soit zoomée sur ma sélection
**Tests de conformité** : 
 1- Vérifier qu'il existe un composant de recherche
 2- Vérifier que la recherche propose les communes de Rennes Métropole
 3 - Vérifier que la recherche propose les zones d'activité de Rennes Métropole
 4 - sélectionner une commune 
 5 - Vérifier que la carte zoome automatiquement sur la commune sélectionnée
 6 - Sélectionner une ZA
 7 - Vérifier que la carte zoome automatiquement sur la ZA sélectionnée

**Comment by Gaetanbrl** [comment]
Suite au point avec Catherine et @Agath21 le 028/07/2020 (voir CR envoyé par mail)  , il n'a pas été précisé de réalisé un zoom sur la commune ou sur une zone particulière.

La recherche doit porter sur l'adresse ou l'établissement (voir maquettes UX).

**Comment by Gaetanbrl** [comment]
Réalisé avec #20  et #24.

En attente pour test sur PF de test.
