### ISSUE TITLE
Accès base de données de l'appli de saisie des données

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#29]
**Description** : Préciser les caractéristiques d'accès à la base de données par l'application php (formulaire de saisie de données)
**User Voice** : En tant qu'utilisateur, je veux que les données transmises par l'application php (formulaire de saisie) soient enregistrées dans la base de données de l'application
**Tests de conformité** : 
 1- Quelle que soit la plateforme appelant, l'API qui liste les moyens de transports retourne des résultats
 2- Quelle que soit la plateforme appelant, l'API qui liste les types d'absences retourne des résultats
 3- Si je cherche une adresse email repertoriée dans le système, alors l'API retourne vrai
 4- Si je cherche une adresse email non repertoriée dans le système, alors l'API retourne faux
 5- Si je cherche demande l'identifiant d'un individu par son adresse email (email existant), alors l'API les retourne
 6- Si je cherche un identifiant d'individu par une adresse email inexistante, alors l'API retourne une erreur
 7- Si je cherche demande les informations horaires d'un individu par son id (id existant), alors l'API les retourne
 8- Si je cherche demande les informations horaires d'un individu par un id inexistant, alors l'API retourne une erreur
 9- Depuis le serveur applicatif (sig-testapp), lancer une commande d'enregistrement de données depuis l'applicatif sur des données fictives
 10- Sur le serveur de données (sig-testgeopublic), vérifier que les données sont bien présentes dans la base de données

**Comment by cbriand** [comment]
Développement en interne d'un contrat d'interfaces avec la base de données cartoHoraires. 
Dans un premier temps, l'API permet de consulter les tables de nomenclature (moyens de transport, type d'absence) et de consulter les données horaires d'un individu

**Comment by Gaetanbrl** [comment]
> Développement en interne d'un contrat d'interfaces avec la base de données cartoHoraires.

@cbriand peux-tu préciser pour quelle phase cela est prévu ? Merci.

**Comment by cbriand** [comment]
L'API est en premier lieu destinée à être utilisée par le formulaire de saisie des données. Toutefois le composant de sélection du moyen de transport pourra aussi l'utiliser afin de construire la liste des moyens de transports référencée en base.
