### ISSUE TITLE
cron de mise à jour app

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#3]
**Description** : Lancer automatiquement un script qui met à jour l'application
**User Voice** : En tant que PO, je souhaite que l'application en production soit la plus à jour possible et la version de qualification intègre les derniers développements
**Tests de conformité** : 
 1- Vérifier que le script dépose le code de la branche master de github sur la plateforme de production (sig-app)
 2- Vérifier que le script dépose le code de la branche develop de github sur la plateforme de qualification (sig-testapp)
 2- Vérifier que le script est lancé automatiquement par cron

**Comment by Gaetanbrl** [comment]
Le script pourra reprendre les explications de l'issue #2.

L'update sera alors simple et consistera en un simple : 

`git pull`

un git checkout pourra être à intégrer si vous souhaitez caler la production sur une branche spécifique. Par exemple :

`git checkout develop`

**Comment by cbriand** [comment]
Cron mis en place sur plateforme de test (branche develop) et plateforme de prod (branche RM-master).
Le script charge le projet Mviewer dont l'appli cartoHoraires est un sous-module (plateforme de test = branche develop,  plateforme de prod = branche master)
