### ISSUE TITLE
Formulaire de saisie : Bouton d'enregistrement et contrôles

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#30]
**Description** : Permettre l'enregistrement des données saisies
**User Voice** : En tant qu'utilisateur, je veux enregistrer les données que j'ai saisies
**Tests de conformité** : 
 1- Charger un formulaire de saisie vierge
 2- Vérifier qu'il existe un bouton "Enregistrer" non cliquable
 3- Saisir les données de tous les jours (horaires+moyens de transport  ou absence)
 4- Vérifier que le bouton "Enregistrer" s'active lorsque toutes les lignes sont correctement renseignées
 5- Vider un champ d'une ligne
 6- le bouton "Enregistrer" se désactive, un message d'information sur la ligne incorrecte indique qu'il manque une information
 7- Vérifier le contrôle similaire sur chaque ligne
 8- Renseigner correctement toutes les lignes
 9 - Le bouton "Enregistrer" s'active
 10- Cliquer sur le bouton "Enregistrer"
 11- la fonction d'enregistrement des données est appelée (vérification dans les logs de l'appli + en base de données)

**Comment by Gaetanbrl** [comment]
Ces points me semblent couverts : 

- [ ] Charger un formulaire de saisie vierge
- [ ] Vérifier qu'il existe un bouton "Enregistrer" non cliquable
- [ ] Saisir les données de tous les jours (horaires+moyens de transport ou absence)

- [ ] Vérifier que le bouton "Enregistrer" s'active lorsque toutes les lignes sont correctement renseignées 
=> Activation si connecté et localisé (les valeurs du formulaires sont saisies par défaut ou selon saisie de l'utilisateur)

- [ ] Vider un champ d'une ligne 
=> Ne peut être vide (absent ou renseigné avec valeurs par défaut)

- [ ] le bouton "Enregistrer" se désactive, un message d'information sur la ligne incorrecte indique qu'il manque une information 
=> Aucune information ne peut manquer si le bouton est dégrisé

- [ ]  Vérifier le contrôle similaire sur chaque ligne
=> Que signifie le `contrôle similaire` ? 

- [ ] Renseigner correctement toutes les lignes

- [ ]  Le bouton "Enregistrer" s'active
=> Si localisé et connecté

- [ ]  Cliquer sur le bouton "Enregistrer"

- [ ]  la fonction d'enregistrement des données est appelée (vérification dans les logs de l'appli + en base de données)
