### ISSUE TITLE
Modification des données d'un utilisateur

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#31]
**Description** : Permettre la modification des données saisies
**User Voice** : En tant qu'utilisateur, je souhaite pouvoir modifier les données que j'ai précédemment saisies
**Tests de conformité** : 
 1- Se connecter avec un compte utilisateur actif
 2- Vérifier que le formulaire de saisie est pré-rempli avec les données de l'utilisateur
 3- Vérifier qu'un bouton actif permet de valider les données telles quelles
 4- Cliquer sur le bouton
 5 -Vérifier en base que la date de dernière saisie est mise à jour avec la date courante pour l'utilisateur
 6- Vérifier que les données de l'utilisateur ne sont pas modifiées en base
 7- Se connecter avec un compte utilisateur actif
 8- Modifier les données de l'utilisateur et cliquer sur "enregistrer"
 9- Vérifier en base que la date de dernière saisie est mise à jour avec la date courante pour l'utilisateur
 10- Vérifier que les données de l'utilisateur sont modifiées en base

**Comment by Gaetanbrl** [comment]
Après avoir sauvegardé plusieurs fois des saisies, je cherche à les récupérer pour les afficher à la connexion (dans le cas où elles existent déjà).

Mais il semblerait que je récupère toutes les données et non pas seulement la saisie. Je crois que les données ne sont pas remplacées en base mais sauvegardées comme des nouveaux enregistrements. 

J'ai actuellement  donc 42 retours pour (2*7 infos) * 3 saisies.

Est-ce normal ? Si oui comment les différencier ?

**Comment by Gaetanbrl** [comment]
Ces points me semblent couverts 

- [ ]  Se connecter avec un compte utilisateur actif
- [ ] Vérifier que le formulaire de saisie est pré-rempli avec les données de l'utilisateur
- [ ] Vérifier qu'un bouton actif permet de valider les données telles quelles
- [ ] Cliquer sur le bouton

**Comment by cbriand** [comment]
validé
