### ISSUE TITLE
Init module et template fixe

### ISSUE THREAD

**Issue by Gaetanbrl** [sigrennesmetropole/cartoHoraires#32]
### Actions

Créér le module afin de rendre un template fixe à l'écran.

### Détails

Le système de template du Mviewer permet d'afficher des informations au clic sur une ou plusieurs entités d'une couche.
Le template du volet est donc lié à la couche.

Pour cette application, nous devons afficher un bandeau de manière fixe et sans dépendance aux informations de la couche.

Le volet d'information est donc un composant indépendant avec ses propres méthodes (JavaScript) et son propre HTML (représentation).

### Réalisation

Nous utiliserons le système d'extension intégré dans le Mviewer. Il permettra de gérer manuellement tout le code Mviewer sans avoir à modifier le coeur.

Nous pourrons ainsi interagir avec la couche de visualisation carto ou bien directement la créer avec le module à son initialisation.

### Prérequis

Disposer de la version Mviewer >= 3.3.

### User story

En tant qu'utilisateur, je souhaiterai voir sur la droite un bandeau me permettant de modifier les données affichée et consulter les horaires de présence par jour.

**Comment by Gaetanbrl** [comment]
@cbriand je souhaiterai avoir validation pour cette issue.

**Comment by pcocheril** [comment]
@Gaetanbrl c'est ok pour moi, mais je ne sais pas des alternatives ont été discutées et s'il y a débat là-dessus. L'hypothèse présentée dans cette issue me parait correspondre au besoin évoqué.

**Comment by Gaetanbrl** [comment]
Merci @pcocheril ,

La validation est ici utile car c'est Cédric qui gère la création d'issue dans ce projet. C'est donc plus une formalité ici puisqu'elle reprend bien le besoin exprimé et ne fait que détailler l'issue #24.

Pendant la création des issues, nous avons en effet laissé une issue générale (#24) mais j'ai besoin d'avoir une issue précise sur la création du module (découpage des tâches du backlog).

L'idée derrière est normalement de voir l'avancement d'une user story. On peut ainsi voir par user story l'avancement des sous-tâches et identifier exactement sur quelle sous-tâche on bloque, sur laquelle on dépasse le temps prévu (quand il a été prévu) etc...

 > mais je ne sais pas des alternatives ont été discutées

Pas à ma connaissance, je n'en identifie pas non plus
