### ISSUE TITLE
Données - zone d'activité pour la recherche

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#5]

**Comment by Gaetanbrl** [comment]
La recherche portera sur l'adresse ou l'établissement (voir commentaire à propos de la réunion du 02/07/2020 sur l'issue #26)

Si cette fonctionnalité est à intégrer, il est toutefois possible d'utiliser les données de l'open data via l'API.
La fiabilité et la complétude de ces données (ZAC) doit toutefois être validée.

**Comment by Gaetanbrl** [comment]
Je complète : 
Le dernier point avec Catherine a montré qu'il sera possible de faire un affichage des donnée selon une sélection de ZAC non direct.

Une checkbox (voir maquette UX) permettra de choisir sir les les données et histogramme affiche les infos de la zac qui intersecte le centre de la carte ou bien toutes les données de l'emprise.

**Comment by cbriand** [comment]
Couche de données : eco_comm:v_za de notre serveur public de PROD:
id="eco_comm:v_za"
url="https://public.sig.rennesmetropole.fr/geoserver/ows"

**Comment by cbriand** [comment]
Une vue geoserver a été créée pour n'afficher que les ZA terminées : 
id="eco_comm:v_za_terminee"
url="https://public.sig.rennesmetropole.fr/geoserver/ows"
