### ISSUE TITLE
Intégration des données en base

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#6]
Données de test

**Comment by Gaetanbrl** [comment]
Un dump a été fourni par @cbriand.

Dans les premières phases, il est possible d'utiliser ces données directement dans le Mviewer pour la représentation / interrogation des données et création du template.

Ces données seront cependant importantes à mettre en base pour le début des travaux autour du recueil des données.

**Comment by cbriand** [comment]
Services WMS/WFS d'accès aux données montés : 

TEST:
 id="v_horaires"
 url="https://public-test.sig.rennesmetropole.fr/geoserver/app/ows"

PROD:
 id="v_horaires"
 url="https://public.sig.rennesmetropole.fr/geoserver/app/ows"

(actuellement, la base de données de production a été populée avec les données de test)

**Comment by cbriand** [comment]
Ajout de données d'absences sur les individus d'id 1 à 10
