### ISSUE TITLE
Interactions avec slider des heures

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#69]
**En tant qu'utilisateur** je souhaite pouvoir mettre à jour les données affichées sur la carte en fonction de l'heure sélectionnée sans perturber la lecture du panneau d'information

Le slider de temporalité permet de choisir l'heure de visualisation des données.
Une modification de sa valeur ne devrait pas recharger l'histogramme qui est identique quelle que soit l'heure de la journée.
Le slider pourrait être plus user-friendly. Quand on le glisse à gauche ou droite, j'aimerais connaitre en temps réel la valeur sur laquelle je me positionne. Actuellement, cette valeur ne se met à jour que lorsqu'on lâche la souris.

**Comment by Gaetanbrl** [comment]
Modification réalisées.

A tester sur la plateforme de test à la prochaine mise à jour.

**Comment by cbriand** [comment]
OK, ça fonctionne bien.
Est-il possible de revoir le style du composant slider pour s'approcher au mieux de la maquette (couleurs du bouton et de la barre de fond, règle de mesures en dessous) ?

**Comment by Gaetanbrl** [comment]
oui @Agath21 refera une passe sur le design et CSS  de l'appli.

**Comment by cbriand** [comment]
Il faudrait aussi désactiver l'interaction entre le slider et les chiffres-clés qui ne sont pas impactés par l'heure

**Comment by Gaetanbrl** [comment]
@cbriand ta demande est liée à  #72.

un commit a été fait sur ce point. Un merge vers develop est nécessaire. Je ferai un cherry pick dans la journée pour un merge isolé de ce commit.
