### ISSUE TITLE
Incohérence : clusters affichés sur la carte, mais pas d'info dans le panneau

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#71]
**En tant qu'utilisateur** je veux que le panneau d'information reflète les données de la carte.

Après un dezoom, on peut se trouver en situation où le panneau d'information indique n'affiche rien (histogramme, stats de saisies) et nous informe qu'il faut zoomer pour obtenir des infos alors qu'il existe des points sur la carte.

![image](https://user-images.githubusercontent.com/38095778/89617908-5537de80-d88b-11ea-83e6-b8598fcf8207.png)

Solution 1 : (ma préférence) Ne pas obliger un niveau de zoom minimum pour afficher les données dans le panneau d'informations ==> Risque sur les performances  
Solution 2 : (si obligation à cause des performances) Faire disparaitre les clusters de la carte lorsque le niveau de zoom minimum n'est pas atteint ==> Risque d'incompréhension de l'utilisateur

**Comment by Gaetanbrl** [comment]
> Ne pas obliger un niveau de zoom minimum

Le niveau de zoom est une configuration du plugin, cela relèvera de l'administration et non du développement.

Comme échangé en début de semaine sur ce point,  par défaut je n'aurai rien affiché, c'est mieux pour les performances car il y aura beaucoup de données.

Le fait de n'afficher sur la carte des données qui ne sont en réalité pas totalement celles que l'on affiche impose ce type d'affichage.

**On retrouvera par exemple une autre situation de ce type :** 

Je suis un utilisateur et je sélectionne 4h00 le matin le lundi. Il n'y aura aucune donnée sur la carte mais le graphique affichera bien les données pour le lundi, sans prendre en compte l'horaire.

**Comment by Gaetanbrl** [comment]
La propriété "zoomLvl" permettra de configurer le niveau de zoom pour accéder aux information du diagramme et les informations liées selon un niveau de zoom souhaité.

**Comment by Gaetanbrl** [comment]
Quelle suite pour cette issue @cbriand ?

**Comment by Gaetanbrl** [comment]
A mettre dans la doc !
