### ISSUE TITLE
Libellé sur stats absences

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#72]
Les stats d'absence concernent la journée complète et n'est pas dépendante de l'heure.
==> Modifier le libellé de la stat d'absence  : 
"XX personnes
sont en télétravail ou absentes
Pour la journée et la zone sélectionnée"

![image](https://user-images.githubusercontent.com/38095778/89618933-58cc6500-d88d-11ea-9f83-550d27266cd1.png)

**Comment by Gaetanbrl** [comment]
Modification faites, à pousser et merger.
