### ISSUE TITLE
Mécanique de détection de l'envoi du mail de rappel et envoi du mail

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#8]
**Description** : Envoyer un mail de demande de renouvellement des horaires à l'utilisateur
**User Voice** : En tant qu'utilisateur, je veux est prévenu lorsque mes horaires arrivent à expiration
**Tests de conformité** : 
 1- Vérifier qu'un script qui vérifie les comptes utilisateur se lance quotidiennement
 2- Vérifier que le script agit sur les comptes utilisateurs dont la date de dernière mise-à-jour a dépassé 6 mois :
- Si la date de dernière relance est nulle ou date de plus d'un mois, envoi d'un mail de relance de saisie des horaires (= mail envoyé tous les mois)
 3- Vérifier le contenu du mail : 
     - URL de l'écran de connexion
     - si 5ème relance, prévenir que le compte sera désactivé au bout d'un mois

**Comment by Gaetanbrl** [comment]
> si 5ème relance, prévenir que le compte sera désactivé au bout d'un mois

@cbriand est-ce prévu côté backend ?

**Comment by cbriand** [comment]
Développé sur l'API interne
