### ISSUE TITLE
Recherche d'établissements sur la base sirene à revoir

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#81]
**PROBLEME 1 :** La recherche d'établissements est trop restrictive car recherche une dénomination exactement égale à la valeur saisie. Il vaut mieux utiliser l'opérateur : au lieu de =

Exemple : sur la saisie "orange"
Actuellement (opérateur =), seuls les établissements qui ont exactement la dénomination "ORANGE" sont retournés
https://data.rennesmetropole.fr/api/records/1.0/search?q=denominationunitelegale%20=%20orange&dataset=base-sirene-v3-ss 

Opérateur : , tous les établissements qui ont ont le mot "ORANGE" dans  la dénomination sont retournés
https://data.rennesmetropole.fr/api/records/1.0/search?q=denominationunitelegale:orange&dataset=base-sirene-v3-ss 

Il me semble que l'API ne permet pas de faire une LIKE vraiment poussée. Par exemple, la saisie "oran" ne retourne aucun résultat quand on pourrait s'attendre à avoir tous les établissements qui ont la sous-chaine "oran" dans leur dénomination. Je me renseigne auprès de l'administrateur de l'API pour savoir si c'est possible de faire une vraie recherche like. 

**PROBLEME 2 :** Le retour de plusieurs résultats est mal géré. Une seule proposition est montrée à l'écran.
Par exemple, la saisie "ORANGE" dans le composant n'affiche que ORANGE - RENNES alors qu'on devrait avoir les 5 résultats dans la liste des propositions.
==> Peut-on avoir demander plus de résultats (10) et afficher tous les résultats à l'écran ?
==> Pour bien distinguer les résultats, peut-on afficher un libellé composé des attributs <denominationunitelegale> - <adresseetablissement> <libellecommuneetablissement> et les trier par ordre alphabétique ?

**Comment by Gaetanbrl** [comment]
> La recherche d'établissements est trop restrictiveTest avec le remplacement de = par : tel que l'URL de requête devient : 

Test du nombre de résultat avec `open` :

Résultat avec `:` => 29 nhits
Résultat avec `=` => 29 nhits


Test du nombre de résultat avec `orange` :

Résultat avec `:` => 72 nhits
Résultat avec `=` => 72 nhits


Je ne vois pas de différence sur le nombre de résultat retourné. La documentation ODS précise pour `id_field:value` :

`returns every record containing the string explore in the column named action`

@cbriand je vais tout de même faire la modification car l'opérateur d'égalité n'est pas dans la documentation mais en l'état je ne suis pas convaincu de la différence avec le égal `=`.

**Comment by Gaetanbrl** [comment]
> Le retour de plusieurs résultats est mal géré
Actuellement le code filtre la liste retournée sur le code SIREN. Si le code SIREN est déjà dans les résultats alors on ne l'ajoute pas une seconde fois.

Le code est ici : 

https://github.com/sigrennesmetropole/cartoHoraires/blob/506397d48d27fa778c4ffaba184b24daa7c53f4e/addons/cartohoraires/js/main.js#L361-L370

Peux-tu me donner les champs que tu souhaiterai voir afin d'avoir une première précision des informations à voir dans la proposition de résultat ?

Voici les champs retournés : 

            "geolocetablissement": [48.132754, -1.639344],
            "siretsiegeunitelegale": "38103128500491",
            "soussectionetablissement": "Programmation, conseil et autres activites informatiques",
            "naturejuridiqueunitelegale": "Soci\u00e9t\u00e9 par actions simplifi\u00e9e \u00e0 associ\u00e9 unique ou soci\u00e9t\u00e9 par actions simplifi\u00e9e unipersonnelle",
            "activiteprincipaleunitelegale": "62.02A",
            "typevoieetablissement": "Rue",
            "adresseetablissement": "12 RUE PATIS TATELIN",
            "groupeunitelegale": "Conseil informatique",
            "classeetablissement": "Conseil en systemes et logiciels informatiques",
            "denominationunitelegale": "OPEN",
            "activiteprincipaleetablissement": "62.02A",
            "trancheeffectifsunitelegale": "2000 \u00e0 4999 salari\u00e9s",
            "datefermetureetablissement": "2008-10-15",
            "datederniertraitementetablissement": "2010-04-18T05:48:57+00:00",
            "populationcommuneetablissement": 211373.0,
            "siren": "381031285",
            "numerovoieetablissement": "12",
            "superficiecommuneetablissement": 5036,
            "statutdiffusionunitelegale": "O",
            "l1_adressage_unitelegale": "OPEN",
            "nomenclatureactiviteprincipaleetablissement": "NAFRev2",
            "divisionunitelegale": "Programmation, conseil et autres activites informatiques",
            "nombreperiodesetablissement": 3,
            "sectionunitelegale": "Information et communication",
            "nic": "00293",
            "siret": "38103128500293",
            "anneeeffectifsunitelegale": "2017",
            "nicsiegeunitelegale": "00491",
            "libellevoieetablissement": "PATIS TATELIN",
            "etatadministratifetablissement": "Ferm\u00e9",
            "groupeetablissement": "Conseil informatique",
            "datecreationunitelegale": "1991-01-21",
            "codearrondissementetablissement": "3",
            "departementetablissement": "ILLE-ET-VILAINE",
            "caractereemployeurunitelegale": "Oui",
            "etatadministratifunitelegale": "Active",
            "categorieentreprise": "ETI",
            "categoriejuridiqueunitelegale": "5720",
            "altitudemoyennecommuneetablissement": 41.0,
            "codeepcietablissement": "243500139",
            "etablissementsiege": "non",
            "codecommuneetablissement": "35238",
            "regionetablissement": "BRETAGNE",
            "sectionetablissement": "Information et communication",
            "economiesocialesolidaireunitelegale": "N",
            "nomenclatureactiviteprincipaleunitelegale": "NAFRev2",
            "coderegionetablissement": "53",
            "datecreationetablissement": "2005-10-31",
            "caractereemployeuretablissement": "Oui",
            "soussectionunitelegale": "Programmation, conseil et autres activites informatiques",
            "epcietablissement": "Rennes M\u00e9tropole",
            "libellecommuneetablissement": "RENNES",
            "divisionetablissement": "Programmation, conseil et autres activites informatiques",
            "anneecategorieentreprise": "2017",
            "statutdiffusionetablissement": "O",
            "codepostaletablissement": "35700",
            "datederniertraitementunitelegale": "2020-07-03T03:38:03+00:00",
            "datedebutetablissement": "2008-10-15",
            "classeunitelegale": "Conseil en systemes et logiciels informatiques",
            "indicerepetitionetablissement": "A",
            "codedepartementetablissement": "35",
            "trancheeffectifsetablissement": "Etablissement non employeur"

**Comment by Gaetanbrl** [comment]
> Actuellement le code filtre la liste retournée sur le code SIREN. Si le code SIREN est déjà dans les résultats alors on ne l'ajoute pas une seconde fois.

* Exemple avec la recherche "open" => seulement 2 code SIREN retournés sur les 5 résultats retournés par l'API

x4 => 381031285
x1 => 363 789045945

Exemple avec la recherche "orange" => seulement 1 code SIREN retournés sur les 5 résultats  retournés par l'API

x5 => 380129866

En réalité, c'est l'API qui retourne les mêmes éléments quand on ajoute la limite "rows=5" dans la requête.

**Comment by Gaetanbrl** [comment]
Je viens de faire la modification dans le code pour avoir une gestion manuelle du nombre de résultat.

On a en effet plus de retours.

![image](https://user-images.githubusercontent.com/16317988/90140128-93e10380-dd79-11ea-970e-4b52838900a4.png)

**Comment by cbriand** [comment]
Pour notre utilisation, il vaut mieux filtrer sur le code SIRET (établissement) que sur le code SIREN (entreprise). L'utilisateur aura plus de chance de retrouver le site où il travaille.

Pour l'affichage, il nous faudrait le format denominationunitelegale - adresseetablissement libellecommuneetablissement (désolé, j'avais mis les champs entre chevrons et github a voulu interpréter ma saisie)

**Comment by Gaetanbrl** [comment]
> Pour l'affichage, il nous faudrait le format denominationunitelegale - adresseetablissement libellecommuneetablissement

Ce résultat convient mieux ? 

J'ai augmenté à 10 le nombre d'affichage. Bien entendu c'est inséré en tant que paramètre du plugin modifiable sans aller dans le code.

![image](https://user-images.githubusercontent.com/16317988/90141071-eb33a380-dd7a-11ea-81ac-c887aa1783c7.png)


![image](https://user-images.githubusercontent.com/16317988/90141095-f38bde80-dd7a-11ea-8a55-1f9a51b13c14.png)

**Comment by cbriand** [comment]
SUPER !
Merci

**Comment by Gaetanbrl** [comment]
Merci pour les retours @cbriand , ca permet de mieux définir ce que l'on souhaite voir.

C'est en local pas encore poussé. Je ferai une PR spécifique sur develop d'ici demain soir.

**Comment by Gaetanbrl** [comment]
@cbriand c'est normalement testable sur la PF de test.

**Comment by cbriand** [comment]
Retirer les doublons de la liste + ne pas se limiter à 10 résultats

Exemple :  quand on tape rennes metropole, il y a 5 résultats pour l'adresse 4av Henri Fréville
![image](https://user-images.githubusercontent.com/38095778/90412093-f48b7b80-e0ac-11ea-99d2-0d2e565df78a.png)

Par ailleurs, si la recherche retourne plus de 10 résultats, il faudrait pouvoir tous les afficher. Possibilité de mettre un scroller sur la liste de résultats ?

**Comment by Gaetanbrl** [comment]
> ne pas se limiter à 10 résultats
C'est un paramètre dans la config du plugin afin d'être modifiable par un administrateur
`"maxsiren": 10`

> Retirer les doublons de la liste
Bien vu !

> Possibilité de mettre un scroller sur la liste de résultats

L'objectif de ce type de composant est d'abord de faire des propositions afin que l'utilisateur affine en fonction des propositions affichées en dessous.

Le scroller est possible mais je n'en ai jamais vu sur ce type de recherche avec autocomplétion.

**Comment by cbriand** [comment]
Pour pouvoir affiner la recherche, il faudrait aussi que les adresses et communes soient pris en compte dans la recherche (exemple : tous les établissements qui s'appellent ORANGE ne sont pas retournés par la recherche, et on ne peut pas affiner plus que le nom)

**Comment by Gaetanbrl** [comment]
> Pour pouvoir affiner la recherche, il faudrait aussi que les adresses et communes soient pris en compte dans la recherche

Ok, à voir selon les possibilités de l'API.

**Comment by Gaetanbrl** [comment]
Vu avec l'API : 

* Utilisation des AND, OR pour rechercher sur un champ ou plusieurs autres

q=(denominationunitelegale:orange OR departementetablissement:orange)

* Utilisation des facets

A regarder plus en détail selon la doc mais les facets peuvent potentiellement être un moyen d'affiner la recherche.
https://help.opendatasoft.com/apis/ods-search-v1/#using-facets

**Comment by Gaetanbrl** [comment]
Je complète avec la doc : 

`:, -, ==: return results whose field exactly matches the given value (granted the fields are of text or numeric type)`

Il ne semble donc pas y avoir d'opérateur LIKE.

https://help.opendatasoft.com/apis/ods-search-v1/#query-language

**Comment by Gaetanbrl** [comment]
Nous avons maintenant une nouvelle configuration du plugin pour mieux gérer la recherche.

```
        "sirenConfig": {
            "filters": ["denominationunitelegale", "adresseetablissement"],
            "operator": "OR",
            "url": "https://data.rennesmetropole.fr/api/records/1.0/search",
            "dataset": "base-sirene-v3-ss",
            "max": 30
        }
```

* **filters** : Recherche la valeur exacte dans les champs présents dans cette liste.

Si vide, la recherche sera du type `q=maVal`. Dans ce cas, le service effectuera un LIKE dans tous les champs du dataset.
* **operator** : Opérateur (OR ou NOT ou AND) pour séparer les champs (si non vide et > 1 filtre)
* **url** : URL du service
* **dateset** : ID du jeu de données à utiliser
* **max** : nombre de résultat(s) à afficher

**Comment by Gaetanbrl** [comment]
> Retirer les doublons de la liste + ne pas se limiter à 10 résultats

Comme demandé précédemment, nous avons filtré les résultat sur le numéro SIRET. Or, nous pouvons avoir plusieurs numéros SIRET pour un même SIREN.

Ce que nous voyons est un label identique mais ne représente pas des résultats identique (~pas de doublons).

* Exemple :

![image](https://user-images.githubusercontent.com/16317988/91198358-be797780-e6fc-11ea-8626-29391ec7a2c2.png)


Nous avons ces codes SIRET (10 codes différents ==> Filtre qui fonctionne).
`["243500139", "243500139", "243500139", "243500139", "243500139", "243500139", "243500139", "243500139", "243500139", "243500139"]`

Et nous avons ces codes SIREN :
`["24350013900270", "24350013900288", "24350013900015", "24350013900080", "24350013900023", "24350013900098", "24350013900056", "24350013900254", "24350013900106", "24350013900148"]`

Le résultat `RENNES METROPOLE - 4 AV HENRI FREVILLE RENNES` est une entité avec un code SIREN unique mais qui correspond à plusieurs codes SIRET différents.

La définition explique cela : 

* Le SIREN est attribué une seule fois au moment de l’inscription de la société dans la base SIRENE de l’INSEE
* Le SIRET est composé de 14 chiffres. Ces chiffres correspondent au  numéro SIREN + un numéro complémentaire appelé NIC (numéro interne de classement)


Donc on a deux solutions : 
* Remettre le filtre sur le numéro SIREN
* Modifier l'intitulé et afficher le champ `enseigne1etablissement` qui donne plus de détails :

![image](https://user-images.githubusercontent.com/16317988/91199359-14025400-e6fe-11ea-852e-169a7ca032e1.png)

**Comment by Gaetanbrl** [comment]
Modifications apportées dans le commit cité au dessus : 

* Configuration plus souple pour plus d'autonomie dans la configuration (dont limitation du nombre de résultats)
* Scroll dans le template pour la visualisation des résultat avec une limite de hauteur
* Modification des libellés afin de ne plus voir de faux doublons
