### ISSUE TITLE
Chargement sous firefox impossible

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#84]
La carte répond bien sous chrome, mais ne se charge pas sous firefox (version déployée sur les postes RM : 60.7.0esr) .

**Console :** 
![image](https://user-images.githubusercontent.com/38095778/90382967-cc395800-e07f-11ea-9182-4f09d8ba9a86.png)

**Comment by cbriand** [comment]
Pour information, les autres cartes mviewer se chargent bien sous firefox

**Comment by Gaetanbrl** [comment]
Cette erreur est également présent sur FF 79.0 (64 bits) mais n'empêche pas le fonctionnement.

La carte et le graphique semblent bien se charger.

Erreur chargement XML : 
```
Erreur d’analyse XML : mal formé
Emplacement : https://testapp.sig.rennesmetropole.fr/mviewer/apps/cartoHoraires/addons/cartohoraires/templates/form.mst
```

L'erreur suivante est un soucis dans le XML  (balise fermante manquante ou autre...).


Ce qui m'inquiète plus ce sont les erreurs au dessus car les autres fichiers JS ne semblent pas se charger si j'en crois tes erreurs. Donc pas de carte...

**Comment by Gaetanbrl** [comment]
> Pour information, les autres cartes mviewer se chargent bien sous firefox

La base se chargerait bien sans le plugin cartoHoraire. C'est la complexité du module qui génère les erreurs d'appels car ce sont les fichiers de ce module qui ne semblent pas bien se charger.

**Comment by Gaetanbrl** [comment]
Après plusieurs refresh j'ai bien un soucis de chargement qui doit être identique. Je reproduis donc. C'est typique d'un fichier qui ne se charge pas ou d'un JS avec une erreur bloquante.

Idem sur Chrome j'ai le même problème tout d'un coup.

**Comment by Gaetanbrl** [comment]
* Erreur XML mal formé 

Je confirme, la syntaxe requise par le navigateur ne correspond pas à la web doc mozilla.

https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input

De plus, le paramètre `required` pourtant existant et encore compatible, même documenté, génère cette erreur.

Donc deux erreurs : 

* Nécessite une balise fermante
* N'accepte pas le paramètre `required`

Voici l'exemple fourni par mozilla, cet exemple est à respecter dans le code et c'est bien déjà le cas : 

https://developer.mozilla.org/fr/docs/Web/HTML/Element/Input


Cette erreur est donc pour moi à ignorer.

**Comment by Gaetanbrl** [comment]
> SyntaxError : bad method definition

Cette erreur est liée à votre version Firefox et semble ne pas supporter l'utilisation des class static JavaScript utilisés par le module.

Un remaniement / modification de l'organisation fondamentale du code est nécessaire pour être compatible avec FF 60.7.0esr.

**Comment by Gaetanbrl** [comment]
**Résolution :**

* Déclaration des propriété de la class et déclaration des propriété dans le constructor
```
class Graph {
    propsA = null;
    /**
     * Constructor
     */
    constructor(propsA = null) {
        this.propsA = propsA;
    }
```

**Devient :** 
```
class Graph {
    /**
     * Constructor
     */
    constructor(propsA = null) {
        this.propsA = propsA;
    }
```

* Suppression des méthode en tant que propriété
`getInfos = function () {} 
`
Devient : 
`getInfos()`


_Fonctionnel avec FF 60.7.0esr (64bits) et Chrome 84.0.4147.125 (Build officiel) (64 bits)._

**Comment by Gaetanbrl** [comment]
@cbriand à tester et fermer si résultat de test = OK.

**Comment by cbriand** [comment]
![image](https://user-images.githubusercontent.com/38095778/90484146-167d1080-e136-11ea-97bd-a523a9931cb3.png)
