### ISSUE TITLE
Mauvais résultat dans stats XX personnes ont saisi leurs horaires/XX personnes absentes

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#87]
Les stats "XX personnes ont saisi leurs horaires" et "XX personnes sont en télétravail ou absentes" retourne le nombre de saisies d'un jour et non pas le nombre de personnes.
Généralement, les personnes ont deux saisies par jours ou une absence, mais la structure de la base tolère des saisies plus atypiques

Il faut compter le nombre d'individu_id uniques sur le jour affiché

Exemple, le lundi, il devrait y avoir 3397 personnes qui ont saisi leurs horaires dont 5 personnes absentes

**Comment by Gaetanbrl** [comment]
Donc si je comprend bien on affiche le nombre de personne qui ont fait des saisies et non le nombre de saisies ? @cbriand

**Comment by cbriand** [comment]
Oui, c'est ça

**Comment by Gaetanbrl** [comment]
Modification faite.
Par contre je retombe sur 3392 présents le lundi et non 3397 présents.

![image](https://user-images.githubusercontent.com/16317988/91203006-e53aac80-e702-11ea-97ae-8b4319040946.png)
