### ISSUE TITLE
Regroupement des saisies par paliers de 15 minutes

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#89]
Pour la visualisation des horaires, créer des groupes de 15 minutes. Principe habituellement retenu, associer un horaire sur le groupe de 15 minutes précédent. Par exemple : un horaire à 7h14 fait parti du groupe de 7h00.

==> Impact sur la carte et sur l'histogramme

Le paramètre de 15 minutes peut-il être configurable si besoin de créer des tranches plus larges ou plus précises ? (même paramètre utilisé pour le slider d'heures)

**Comment by cbriand** [comment]
On a vu la semaine dernière que le composant timePicker ne permettait pas de forcer un palier de 15 sur la saisie des minutes. A la saisie, il est possible d'enregistrer des 7h14.

**Comment by cbriand** [comment]
Mécanique de regroupement des données à faire à la visualisation des données et non pas à l'enregistrement pour conserver l'intégrité des données.
==> mécanique à développer dans le code
==> durée de la tranche configurable dans fichier de conf (second temps)

**Comment by Gaetanbrl** [comment]
Valeurs regroupés par palier et configurable via le paramètre "graphStep" du fichier config.json de l'addon cartoHoraire :

https://github.com/sigrennesmetropole/cartoHoraires/blob/cdfafba6086b304572dea7fbf1c8ec3035178558/addons/cartohoraires/config.json#L39

![image](https://user-images.githubusercontent.com/16317988/91191183-be757980-e6f4-11ea-93e5-9e242dd61aa6.png)

**Comment by Gaetanbrl** [comment]
J'avais oublié de regrouper les données par horaire après l'arrondi à l'échelle souhaitée (15min).

Modification faite dans le commit 6cb04b6c3a36988d5758b8be33afd9c4d5822269 .

**Comment by cbriand** [comment]
Décalage de 15 minutes dans les affichages d'histogramme : 

Sur la journée du lundi, je compte en base 352 saisies à 08:30, 50 à 08h35, 1 à 08:39, 118 à 08h40 ==> pour un total regroupé à 521 à 08h30

Dans le diagramme, les 521 résultats sont présentés à 08h45.

**Comment by Gaetanbrl** [comment]
L'arrondis ce fait au 15min supérieur.

Pour tes données on a donc en théorie : 
* 352 saisies à 08:30 ==> 352 à 8h30
* 50 à 08h35, 1 à 08:39, 118 à 08h40 ==> 169 à 8h45

J'en ai sur le graphique 521 à 8h45 et 305 à 8h30. Etrange.... je vais check les données en revenant.

**Comment by cbriand** [comment]
La demande était d'arrondir au 15min inférieur. Une saisie à 07h14 se retrouve dans le groupe de 07h00.

**Comment by Gaetanbrl** [comment]
> arrondir au 15min inférieur

Ca explique tout.

**Comment by Gaetanbrl** [comment]
>  pour un total regroupé à 521 à 08h30

On y est c'est mieux.

![image](https://user-images.githubusercontent.com/16317988/91306725-3d2ded80-e7ad-11ea-943e-ec1c05f03b5a.png)
