### ISSUE TITLE
Visu des horaires sur la carte - quelle tolérance géographique pour rassembler des points dans un même cluster

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#90]
Existe-t-il une tolérance géographique pour regrouper des points dans un même cluster ?

Exemple : ces points ne devraient-ils pas être réunis dans le même cluster ? (points de lundi à 8h00)
![image](https://user-images.githubusercontent.com/38095778/90414737-75984200-e0b0-11ea-98b9-7b707c47bd3e.png)

**Comment by Gaetanbrl** [comment]
> Existe-t-il une tolérance géographique pour regrouper des points dans un même cluster ?
La tolérance est en pixels.
Actuellement nous sommes à 0 pixels afin de regrouper toutes les features à la même adresse (souhaits formulé au départ).

> Exemple : ces points ne devraient-ils pas être réunis dans le même cluster ? (points de lundi à 8h00)
Si ces point ne sont pas dans le même clusters alors ils sont à des coordonnées différentes.

**Comment by Gaetanbrl** [comment]
Doublon avec #132

**Comment by cbriand** [comment]
corrigé en même temps que #132 : utilisation de l'attribut distance du fichier customlayers.etablissement.js avec une valeur de 10
