### ISSUE TITLE
IHM - intertitre sur filtre des données 

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#91]
Ajouter un intertitre "Affiner les résultats" avant les filtres de temporalité et de mode de transport

![image](https://user-images.githubusercontent.com/38095778/90415018-cf990780-e0b0-11ea-9fcc-618ef066b7d7.png)

**Comment by Gaetanbrl** [comment]
@Agath21 c'est pour toi ?

**Comment by Agath21** [comment]
Modification réalisée - à valider
![image](https://user-images.githubusercontent.com/22764056/90491755-a58f2600-e140-11ea-9f66-7a5ced92dc39.png)

**Comment by cbriand** [comment]
Oui, ça me va très bien : c'est validé !
