### ISSUE TITLE
Histogramme - décalage d'1h sur les résultats

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#93]
Les valeurs présentées par l'histogramme sont décalées d'1 heure
Sur l'emprise complète des résultats, nous devrions avoir ces valeurs d'arrivée sur le lundi : 
**Horaire | Nombre**
06:00:00 | 1
06:40:00 | 1
06:45:00 | 1
06:50:00 | 1
07:00:00 | 7
07:05:00 | 1
07:10:00 | 1
07:15:00 | 9
07:20:00 | 7
07:25:00 | 3
07:30:00 | 61
07:35:00 | 11
07:40:00 | 18
07:45:00 | 51
07:50:00 | 40
07:54:00 | 1
07:55:00 | 20
07:58:00 | 1
08:00:00 | 230
08:03:00 | 1
08:05:00 | 32
08:10:00 | 48
08:12:00 | 1
08:15:00 | 169
08:20:00 | 89
08:25:00 | 47
08:30:00 | 352
08:35:00 | 50
08:39:00 | 1
08:40:00 | 118
08:45:00 | 255
08:50:00 | 130
08:55:00 | 55
09:00:00 | 612
...

![image](https://user-images.githubusercontent.com/38095778/90498329-72e92b80-e148-11ea-9be2-490dc3fe4a43.png)

La couche de consultation v_horaires retourne les bons horaires

**Comment by Gaetanbrl** [comment]
Peux-tu me donner ces mêmes résultats avec les ID des individus ?
Merci.

**Comment by Gaetanbrl** [comment]
Pour la construction du graph le format HH:mm:ss:Z est interprété avec +2h .

Exemple avec ces données : 
```
absence: false
absence_id: null
absence_lib: null
caduc: false
date_saisie: "2020-08-05Z"
geometry: e {…}
horaire: "17:35:00Z"
id: 25854
individu_id: 3403
jour: 2
mouvement: "D"
moytransp_id: 9
transport_lib: "Voiture (seul(e))"
```

La librairie m'indique un horaire +2h : 
```
moment('17:30:00Z', 'HH:mm:ssZ').format('HH:mm:ss') 
//19:30:00
```

**Comment by Gaetanbrl** [comment]
Voici ce que j'ai sur mes données sans la lib pour traiter les labels / lecture de l'heure : 

05:00:00Z: 1
05:40:00Z: 1
05:45:00Z: 1
05:50:00Z: 1
06:00:00Z: 7
06:05:00Z: 1
06:10:00Z: 1
06:15:00Z: 9
06:20:00Z: 7
06:25:00Z: 3
06:30:00Z: 61
06:35:00Z: 11
06:40:00Z: 18
06:45:00Z: 51
06:50:00Z: 40
06:54:00Z: 1
06:55:00Z: 20
06:58:00Z: 1
07:00:00Z: 230
07:03:00Z: 1
07:05:00Z: 32
07:10:00Z: 48
07:12:00Z: 1
07:15:00Z: 169
07:20:00Z: 89
07:25:00Z: 47
07:30:00Z: 352
07:35:00Z: 50
07:39:00Z: 1
07:40:00Z: 118
07:45:00Z: 255
07:50:00Z: 130
07:55:00Z: 55
08:00:00Z: 612
08:03:00Z: 1
08:05:00Z: 98
08:08:00Z: 1
08:10:00Z: 110
08:15:00Z: 281
08:20:00Z: 92
08:25:00Z: 48
08:30:00Z: 233
08:35:00Z: 13
08:40:00Z: 14
08:45:00Z: 34
08:50:00Z: 2
08:55:00Z: 2
09:00:00Z: 31
09:10:00Z: 1
09:12:00Z: 1
09:15:00Z: 1
09:30:00Z: 4
14:35:00Z: 1
15:15:00Z: 1
15:20:00Z: 1
15:25:00Z: 1
15:35:00Z: 7
15:40:00Z: 1
15:45:00Z: 1
15:50:00Z: 9
15:55:00Z: 7
16:00:00Z: 3
16:05:00Z: 61
16:10:00Z: 11
16:15:00Z: 18
16:20:00Z: 51
16:25:00Z: 40
16:29:00Z: 1
16:30:00Z: 20
16:33:00Z: 1
16:35:00Z: 230
16:38:00Z: 1
16:40:00Z: 32
16:45:00Z: 48
16:47:00Z: 1
16:50:00Z: 169
16:55:00Z: 89
17:00:00Z: 47
17:05:00Z: 352
17:10:00Z: 50
17:14:00Z: 1
17:15:00Z: 118
17:20:00Z: 255
17:25:00Z: 130
17:30:00Z: 55
17:35:00Z: 612
17:38:00Z: 1
17:40:00Z: 98
17:43:00Z: 1
17:45:00Z: 110
17:50:00Z: 281
17:55:00Z: 92
18:00:00Z: 48
18:05:00Z: 233
18:10:00Z: 13
18:15:00Z: 14
18:20:00Z: 34
18:25:00Z: 2
18:30:00Z: 2
18:35:00Z: 31
18:45:00Z: 1
18:47:00Z: 1
18:50:00Z: 1
19:05:00Z: 4

**Comment by Gaetanbrl** [comment]
@cbriand il faudrait regarder en base si pour un `id_individu` l'heure de saisi est bien la même que celle publiée par le GeoServer.

Nous avons régulièrement des problèmes de ce type entre Oracle et GeoServer. Maintenant nous exposons pour chaque table / vue un champ date_str qui est le champ date converti en String. Ceci permet d'éviter une heure de décalage entre GeoServer et la table.

**Comment by Gaetanbrl** [comment]
> La couche de consultation v_horaires retourne les bons horaires

@cbriand  je te confirme que les données initiales transmises par le GeoServer me retourne 230 features pour le lundi à 07:00:00Z

`h7 = lundi.filter(e => e.getProperties().horaire == '07:00:00Z')`

**Comment by Gaetanbrl** [comment]
A fermer je crois @cbriand
