### ISSUE TITLE
Histogramme - jour sans données

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#96]
Changer le libellé en cas de jour sans données de l'histogramme :
" Aucune donnée à analyser sur le jour et la zone sélectionnés"

![image](https://user-images.githubusercontent.com/38095778/90532458-8eb7f600-e177-11ea-880c-ca8e4ccb5d77.png)

**Comment by Agath21** [comment]
@Gaetanbrl je me charge de cette modification

**Comment by Gaetanbrl** [comment]
Bien noté @Agath21

**Comment by Agath21** [comment]
Modification réalisée - à valider
![image](https://user-images.githubusercontent.com/22764056/90754312-01d97d80-e2da-11ea-9c25-8267ef01e200.png)

**Comment by Gaetanbrl** [comment]
@Agath21 tu fais la demande de PR ? :)

**Comment by Agath21** [comment]
Nan j'ai réalisé la modification sur la branche feature-style-2, c'est seulement à valider par @cbriand

**Comment by Agath21** [comment]
Ou je clos l'issue directement ?

**Comment by cbriand** [comment]
OK, on peut clore
