### ISSUE TITLE
IHM - Texte d'aide sur le filtre zones d'activité

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#97]
Indiquer à l'utilisateur comment filtrer les données par zone d'activité.

Remplacer le sous-texte "Voir uniquement les informations par zone d'activité vue sur la carte" par "Pour consulter les informations d'une zone d'activité, placez la zone d'activité souhaitée sous la croix jaune" ( + alléger le font-weight du sous-texte ?)

**Comment by Gaetanbrl** [comment]
La fenêtre "Documentation" permet d'avoir tout le contenu d'aide nécessaire pour détailler l'utilisation.

Je pense qu'il peut-être intéressant de l'utiliser pour ne pas trop surcharger la zone de filtre / dataviz.

**Comment by Agath21** [comment]
Modification réalisée - à valider
![image](https://user-images.githubusercontent.com/22764056/90754042-aad3a880-e2d9-11ea-8877-24926b30b52c.png)

**Comment by cbriand** [comment]
OK pour la phrase. 
Est-ce qu'il est possible de faire apparaitre cette phrase uniquement quand le bouton switch est sur ON ?
