### ISSUE TITLE
IHM - Revoir la lecture du bandeau d'information

### ISSUE THREAD

**Issue by cbriand** [sigrennesmetropole/cartoHoraires#98]
### TITRAGE
Numéroter les 2 parties (filtre et résultats) pour une meilleure compréhension et modifier/ajouter quelques sous-titres

**Proposition de titres par la com :** 

1- Affiner ma recherche
    Zone géographique
    Temporalité
    Mode de transport

2- Résultats sur la zone et le jour sélectionnés

### COMPOSANT DE SELECTION D'HEURES : 
  - Ajouter des repères sur la ligne de temps (ex : 8h, 12h, 16h, 20h)

### LECTURE DE LA PARTIE RESULTATS
Chiffres-clés : 
  - Diminuer légèrement la taille des iconographies et textes des chiffres-clés pour mettre en avant l'histogramme (info plus importante)
  - Remplacer le raccourci "pers." par "personnes" dans les chiffres-clés

Histogramme :  
  - Titre = "Répartition des arrivées et départs sur une journée"
  - Sous-titre = "Pour la journée, le mode de transport et la zone sélectionnés"   (il manque actuellement le s à sélectionnés)

### FORMULAIRE DE SAISIE
(info à adapter avec nos réflexions sur le formulaire sur la copie des jours)
  - Libellé d'aide sur la copie des données :  "Vos informations ont été copiées jusqu'au vendredi. Si vos horaires et/ ou modes de déplacement varient, merci de mettre à jour les données ci-dessous"

**Comment by cbriand** [comment]
Précisions sur le titrage : 
"1- Affiner ma recherche" remplace "Configurer la carte"
"Zone géographique" = nouveau sous-titre pour la partie regroupant la recherche entreprise/adresse + ZAC
"Temporalité" = idem qu'actuellement
"Mode de transport" = idem qu'actuellement
2- "Résultats sur la zone et le jour sélectionnés" remplace "Visualiser les déplacements sur la zone sélectionnée"

**Comment by Gaetanbrl** [comment]
* 2- Résultats sur la zone et le jour sélectionnés

Avec cette formulation je pense qu'il faut rajouter le mode de transport. Autrement on a l'impression que que ce n'est que dépendant de la zone et de la journée.

* Ajouter des repères sur la ligne de temps (ex : 8h, 12h, 16h, 20h)

Cette évolution doit être réalisable.

![image](https://user-images.githubusercontent.com/16317988/90732255-211cde80-e2cb-11ea-8734-a9d291f3c66d.png)


* Libellé d'aide sur la copie des données :


Actuellement comme ceci, à revoir selon nos réflexion en effet : 

![image](https://user-images.githubusercontent.com/16317988/90732427-5b867b80-e2cb-11ea-9ccb-ff8158d691c0.png)

**Comment by cbriand** [comment]
"2- Résultats sur la zone, le jour et le mode de transport sélectionnés"  : OK pour cette proposition

**Comment by Agath21** [comment]
Modifications des titres réalisées 
![image](https://user-images.githubusercontent.com/22764056/90756791-14a18180-e2dd-11ea-93ae-c648611c15e8.png)

**Comment by cbriand** [comment]
@Agath21, ça me semble pas mal. Est-ce que tu peux pousser la modif sur la branch feature-style-2 pour que je vois ce que ça donne en vrai, stp ?

**Comment by Agath21** [comment]
@cbriand  C'est ok sur la branche feature-style-2

**Comment by Agath21** [comment]
Modifications réalisées : Changement du titre de l'histogramme + réduction des fonts pour les chiffres clés 
![image](https://user-images.githubusercontent.com/22764056/90766755-5ab21180-e2ec-11ea-8e3a-7cd06a590d9e.png)

**Comment by Gaetanbrl** [comment]
@Agath21, voir commit https://github.com/sigrennesmetropole/cartoHoraires/commit/64d95a56803f71ac2496cf2806ddb360236645da.

Le slider ne s'initialise pas correctement. Il faut forcer le refresh à l'initalisation : 
* Ajout d'une méthode `refresh `pour une instance d'un slider
* Appel du `refresh` au déclenchement de l'event `postrender `de la carte (~init)

**Comment by Agath21** [comment]
**Formulaire de saisie**
Modification du style du bouton et ajout du libellé 
![image](https://user-images.githubusercontent.com/22764056/91290875-7c037980-e794-11ea-9818-9814e5364ea8.png)

**Comment by Agath21** [comment]
Modification du texte 
![image](https://user-images.githubusercontent.com/22764056/91413547-951b3180-e84b-11ea-9fa5-7e63d336d3af.png)

**Comment by Gaetanbrl** [comment]
@cbriand  cette issue est à fermer ?

**Comment by cbriand** [comment]
on a mélangé deux sujets dans ce ticket (bandeau +  boutons "copier" du formulaire. La partie Bandeau est ok. 
Le sujet du bouton "copier" peut être suivi dans l'issue #22
